### ISSUE TITLE
Progress bar with decimals in percentage

### ISSUE THREAD

**Issue by 0xiliyan** [mkocansey/bladewind#109]
The progress bar only works with integer percentages, I'd like for it to work with decimals / floats as well, so if I input lets say 55.32% I get this displayed in the label and also reflected in the progress bar (currently I think its parsed as 100% if I pass a float).

**Comment by mkocansey** [comment]
Sure @0xiliyan. Will get this sorted out.

**Comment by mkocansey** [comment]
@0xiliyan `composer update`
