### ISSUE TITLE
Set Dropdown values using Javascript

### ISSUE THREAD

**Issue by resujentoezequiel** [mkocansey/bladewind#112]
Good day,

How can I set the default value to the dropdown from the javascript?

bladewind modal:
![image](https://user-images.githubusercontent.com/43774016/228281357-b63a9470-e436-4878-88c1-ef73c48eb144.png)

javascript:
![image (1)](https://user-images.githubusercontent.com/43774016/228281416-6b097c3e-761c-467e-ab67-63b3a43e59e5.png)

Thank you

**Comment by hamaadraza** [comment]
document.getElementsByName("dropdown").value = value_you_want_to_load;
