### ISSUE TITLE
Unable to locate a class or view for component [frameless].

### ISSUE THREAD

**Issue by sh4msi** [mkocansey/bladewind#122]
hi,

When using the "error page", I face the error of the absence of the frameless component
`Unable to locate a class or view for component [frameless].`

And in use without "frameless", the screen is displayed in a mess.

**Comment by mkocansey** [comment]
Oops. Thanks for bringing this to my attention. Will check and fix right away.

**Comment by mkocansey** [comment]
@sh4msi You'll notice I have this comment on the error pages [documentation page](https://bladewindui.com/extra/error-pages). 

// this is a layout file specific to the documentation that
// just gets rid of the left navigation
// it is not available as a component

The error component is just supposed to sit within your existing website layout.

The frameless file is however available here if you still want to use it. 

https://github.com/mkocansey/bladewind-docs/blob/development/resources/views/components/frameless.blade.php
