### ISSUE TITLE
Ratings precision option

### ISSUE THREAD

**Issue by kalirocket** [mkocansey/bladewind#138]
1. Option that allows user to rate 0.5, 1, 1.5... to 5. When the user hovers halfway on a star it highlights half of the star. If the user hovers to the max width to the right it highlights fully the star. 
At this point when the user hovers and clicks the star to the highlighted part the ratings value is calculated and may include floating number if there were halfway highlighted stars. 

2. A rating option to display stars precisely with rating="X.XX" value up to 2 decimal places. The highlighted stars are displayed precisely based on the rating value.

**Comment by mkocansey** [comment]
@kalirocket I don’t quite understand your comment. Can you be more precise with your explanation. Possibly specify actions that need to be taken.

**Comment by mkocansey** [comment]
@kalirocket thought about this in the beginning but the dropped the idea when things got too complex figuring out how to fill out half of a star. 

Marking this as wontfix for now. Hopefully a community member can reopen and build this into BladewindUI

**Comment by kalirocket** [comment]
@mkocansey Great. I would want to build this functionality into BladewindUI.

**Comment by mkocansey** [comment]
Sure. Give it a shot
