### ISSUE TITLE
[Question] Livewire compatibility 

### ISSUE THREAD

**Issue by robsontenorio** [mkocansey/bladewind#139]
Hi!

Thanks for your nice work :)

Is this package supposed to work with Livewire ?

1) Just tried select component + `wire:model`  and it does not work, once it places `wire:model` on every single option. 

https://bladewindui.com/component/select

2) Also tried input  component with icon + `wire:model.live`and cursor overflows after rerendering page. 

3) It does not accept `wire:key` on `x-bladewind.list-item`

**Comment by mkocansey** [comment]
Thanks @robsontenorio for the kind words and trying out BladewindUI.

No, BladewindUI was not designed with support for Livewire in mind. 
The goal was/is to keep this tied to only blade, tailwindcss and vanilla Javascript to avoid having to keep up with updates made to other libraries (if used within BladewindUI). 

This is why the things you tried in your points 1, 2, 3 did not work. Possibly in future(hopefully after a stable Livewire 3 version), BladewindUI will be refactored to work nicely with Livewire.
