### ISSUE TITLE
Icon from Alert component added in page are hidden when notification is launched

### ISSUE THREAD

**Issue by bhenscamp** [mkocansey/bladewind#142]
The following steps can be followed to replicate the issue.

- add `<x-bladewind::alert show_close_icon="false" show_icon="true">` in page
- add `<x-bladewind::notification />`  in page
- display the page in your browser
- in browser console try `showNotification(
			"test",
			"test",
		);`

- icon from `<x-bladewind::alert show_close_icon="false" show_icon="true">` disappears

it seems that this comes from usage of modal-icon in Alert component, and showNotification remove all icon of this type.

**Comment by mkocansey** [comment]
Thanks @bhenscamp for raising this. Will fix and release an update shortly.

**Comment by mkocansey** [comment]
@bhenscamp this is fixed in `2.2.8`
