### ISSUE TITLE
Laravel mix is not recognizing Tailwind classes in components 

### ISSUE THREAD

**Issue by gsbarbo** [mkocansey/bladewind#16]
When I run "npm run watch" it doesn't save the classes in the components files.

composer.json
        "laravel/framework": "^9.11",
        "mkocansey/bladewind": "^0.1.7",

Package.json
        "postcss": "^8.4.6",
        "postcss-import": "^14.0.2",
        "tailwindcss": "^3.0.18"
        "laravel-mix": "^6.0.6",

tailwind.config.js

    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

webpack.mix.js

mix.js('resources/js/app.js', 'public/js').postCss('resources/css/app.css', 'public/css', [
    require('postcss-import'),
    require('tailwindcss'),
    require('autoprefixer'),
]);

**Comment by mkocansey** [comment]
@gsbarbo I tried replicating your problem with the exact package versions above but got the desired results. 

With `npm run watch` running, 
I edited resources > views > components > bladewind > button.blade.php and added `blur-lg` to line:53
`{{ $attributes->merge(['class' => "bw-button blur-lg $size $type $name $primary_color $is_disabled"]) }}`

My public > css > app.css file got updated with the css for `.blur-lg`.

It will help to know (so I can replicate ditto)
- Which component(s) you tried adding/updating css for
- What css did you add/change.

**Comment by mkocansey** [comment]
@gsbarbo any luck getting this to work?

**Comment by gsbarbo** [comment]
I was maybe premature with opening a ticket or at least I don't remember the exact thing I was looking at. I was looking at the modal component and the widths. (w-1/2 w-1/3 w-1/4 w-1/5 w-1/6) They are in app.css but all the models are the same size (Full width) except for big. Then its small.

**Comment by mkocansey** [comment]
Oh right. The modal one was actually a bug that has been fixed in the current version.
