### ISSUE TITLE
Make Modals Scrollable.

### ISSUE THREAD

**Issue by zaghadon** [mkocansey/bladewind#164]
I have a modal dialog in my app which can get quite long in the y direction. This introduces a problem whereby some of the content of the dialog is hidden off the bottom of the page.

Setting this CSS property would effectively address this situation:

`overflow-y: auto;`

**Comment by mkocansey** [comment]
@zaghadon Considering people have different use cases for modals, a minimum height cannot be defined, beyond which the content of the modal will scroll. It is best (and easier) to define the overflow property on the content you place within the modal. Please see example below.

```
<x-bladewind::modal
    name="tnc"
    title="App Terms and Conditions">
    
    <div class="h-96 overflow-y-scroll">
        ...
        your very long content here
       ...
    </div>

<x-bladewind::modal>
```

Let me know if this helped

**Comment by zaghadon** [comment]
Yes this looks good, I'd try it and thanks for the quick response.

**Comment by zaghadon** [comment]
Unfortunately, this didn't work @mkocansey .

The thing is, when the Modal Element initializes, it sets the children elements into the body, which is siblings with the footer element which contains the action buttons. Therefore setting an overflow to the body doesn't stop the hiding away of the footer sibling. 

Now what I did was simply target the `.bw-modal` class in JS and add the `.overflow-y-scroll` class to it, result achieved, works exactly as intended without altering what already is. 

```javascript
dom_els(".bw-modal").forEach(el => {
  el.classList.add('overflow-y-scroll');
});
```

I added this to my root layout, issue fixed for me. 

My suggestion would be to probably add an option which allows us to set classes on elements which can merge with the elements classes during initialization. Just like normal blade components.

**Comment by mkocansey** [comment]
@zaghadon I am glad you got a JS workaround. I have added 3 options that allow for adding additional css to the modal header, body and footer. I am sure that should cater for altering the modal in most cases. Will push this with a few other updates over the weekend.

**Comment by zaghadon** [comment]
Great 👍
