### ISSUE TITLE
Filter another Select Component's items based on the selected value of another component

### ISSUE THREAD

**Issue by mkocansey** [mkocansey/bladewind#165]
@mkocansey How about filtering another Select Component's items based the selected value of another component?

**For instance:**
There's Component Network to select Network Category
Then there's another Plans component to select Data Plan.

I want to filter Data Plans by the Network category. How do I select the <x-bladewind.select-item />'s that form in the DOM? I mean in the example of the cards, we knew what the DOM elements are and we're able to select it and then apply regex. How do we select the <x-bladewind.select-item />'s in the DOM?

_Originally posted by @zaghadon in https://github.com/mkocansey/bladewind/issues/154#issuecomment-1779987374_

**Comment by asaah18** [comment]
Just so you know, I did that in a project I am working in using javascript to filter options of selection _B_(by targeting their container using javascript and make them `display: None`) when value of selection _A_ changes(triggered by `onChange` callback props).

But a first party solution would definitely be **better**. With a nice **addition** of passing `alpine.js` state to a component

**Comment by zaghadon** [comment]
@asaah18 makes sense. Can you share code snippet for how you implemented that? I guess that could be helpful to the conversation.

**Comment by asaah18** [comment]
> @asaah18 makes sense. Can you share code snippet for how you implemented that? I guess that could be helpful to the conversation. 

Will do when I have the chance to do so

**Comment by asaah18** [comment]
Here's the snippet code I use for filtering a selection based on the value of another selection field

```blade
<main>
        <x-bladewind.select
                color="primary"
                name="department"
                searchable="true"
                multiple="true"
                label_key="name"
                value_key="id"
                flag_key="id"
                placeholder="Department"
                selected_value="{{ old('department') }}"
                onselect="filterEmployees"
                :data="$departments"/>
        <x-bladewind.select
                color="primary"
                name="employees"
                searchable="true"
                label_key="full_name"
                value_key="id"
                flag_key="id"
                placeholder="Employees"
                multiple="true"
                selected_value="{{ old('employees') }}"
                :data="$employees"/>
<script defer>
    const employeeToDepartment = (() => {
        const employeeToDepartment = {};
        for (const employee of @json($employees)) {
            employeeToDepartment[employee.id] = employee.department_id;
        }
        return employeeToDepartment;
    })();

    function filterEmployees(value, label) {
        {{-- get employee options nodes --}}
        const employeesNodes = document.querySelectorAll(bw_employees.selectItems);
        const departments = document.querySelector(bw_department.formInput).value;

        if (departments === "") {
            {{-- show all employees if no department selected --}}
                for (const employeesNode of employeesNodes) {
                {{-- show employee --}}
                    employeesNode.style.display = '';
            }
        } else {
            {{-- show employees from select department only --}}
                for (const employeesNode of employeesNodes) {
                const departmentArray = departments.split(',');
                const employeeID = employeesNode.dataset.value;
                const employeeDepartment = employeeToDepartment[employeeID].toString();
                if (departmentArray.includes(employeeDepartment)) {
                    {{-- show employee --}}
                        employeesNode.style.display = '';
                } else {
                    {{-- hide employee --}}
                        employeesNode.style.display = 'none';
                    {{-- unselect employee --}}
                    bw_employees.unsetValue(employeesNode);
                }
            }
        }
    }
    
</script>
</main>
```

**Comment by mkocansey** [comment]
> ```
> document.querySelector
> ```

@zaghadon, you can resort to a similar solution (temporarily) as @asaah18 posted above, while I work this into the library.

**Comment by mkocansey** [comment]
@asaah18 Sure. I will

**Comment by mkocansey** [comment]
@zaghadon @asaah18 this is now possible in v2.4.4.
https://bladewindui.com/component/select#filtering

**Comment by asaah18** [comment]
That's great, thank you

**Comment by zaghadon** [comment]
Well done @mkocansey and Compliments of the season 🥂

**Comment by asaah18** [comment]
> @zaghadon @asaah18 this is now possible in v2.4.4.
> 
> https://bladewindui.com/component/select#filtering 

That's great, thank you
