### ISSUE TITLE
I believe components doesn't look good in dark mode

### ISSUE THREAD

**Issue by asaah18** [mkocansey/bladewind#176]
Also, I would like to have the option to disable dark mode in bladewindUI components.

**Comment by mkocansey** [comment]
@asaah18 as explained in the [customisation section of the docs](https://bladewindui.com/customization#change-theme), the dark mode colours are picked from what is defined in your project's `tailwind.config.js` file. 

```js
 theme: {
    extend: {
      colors: {
        primary: colors.blue,
        secondary: colors.slate,
        dark: colors.slate,
        ...
```

If the dark mode colours are a bit off for you, you can edit the line that says `dark: colors.slate` and specify your preferred colour from TailwindCSS's [list of colours](https://tailwindcss.com/docs/customizing-colors). 

Currently BladewindUI uses the user's system setting to activate dark mode. Will change this in the next update to depend on your project's dark mode setting. 

```
// tailwind.config.js
module.exports = {
  darkMode: 'media',  // current implementation 
  darkMode: 'class',  // next update will implement this
  // ...
}
```
