### ISSUE TITLE
bw-table class blocking darkmode

### ISSUE THREAD

**Issue by meynot** [mkocansey/bladewind#182]
In table component 
<x-bladewind::table
table class will include bw-table which disable darkmode!

**Comment by mkocansey** [comment]
@meynot thanks for drawing this to my attention. Will provide a fix

**Comment by mkocansey** [comment]
@meynot I couldn't replicate the issue you reported. If you browse any of the BladewindUI docs pages in dark mode, you will notice the table displaying the _Full List of Attributes_ displays well in dark mode. 

Example [https://bladewindui.com/component/checkbox#attributes](https://bladewindui.com/component/checkbox#attributes) 

Am I missing something?

**Comment by meynot** [comment]
I can not see no dark-mode button/checkbox on the site
https://bladewindui.com/component/table
tables are onle light eventhough I followed the installation 
here is an example of what I am having
http://3.70.238.110/
