### ISSUE TITLE
Table component 

### ISSUE THREAD

**Issue by meynot** [mkocansey/bladewind#187]
If single row in Table component, it does not show.

**Comment by meynot** [comment]
I mean when null both include_columns and execlude_columns

**Comment by mkocansey** [comment]
@meynot is it possible to paste your sample code here or you can mail to mike@bladewindui.com. I need to know exactly which attributes you are using so I can replicate the problem.

**Comment by mkocansey** [comment]
@meynot I managed to reproduce the error. Will be fixed in next update.
