### ISSUE TITLE
Consider adding outlined buttons

### ISSUE THREAD

**Issue by BeBel42** [mkocansey/bladewind#188]
Hi,
Thank you for making this awesome library for us, I really appreciate it.

After seeing [the buttons shown in the docs](https://bladewindui.com/component/button), I was thinking that it lacked outlined buttons. Such as [Bootstrap's `btn-outline-*` class](https://getbootstrap.com/docs/4.0/components/buttons/).

We could style the button, customize the library to our needs to get an outlined button, but that may not be as comfortable as just using a `<x-bladewind.button-outline>subscribe now</x-bladewind.button-outline>`

The two options I can see is either create a new blade template, or add a new attribute to the existing `x.bladewind.button` template.

Would you consider adding such buttons into Bladewind?

**Comment by mkocansey** [comment]
@BeBel42 I'm glad you're finding the library useful. You make a good point. I'll add an outline button as an attribute. That way irrespective of what button type (primary, secondary) you're using, it can exist as an outline, in any colour you specify.

**Comment by mkocansey** [comment]
@BeBel42 Now available in #194 

Docs: [https://bladewindui.com/component/button#outline](https://bladewindui.com/component/button#outline)
