### ISSUE TITLE
can we install in the laravel 8 in my existing project

### ISSUE THREAD

**Issue by Tejas20002** [mkocansey/bladewind#19]
Problem 1
    - Root composer.json requires mkocansey/bladewind ^0.1.7 -> satisfiable by mkocansey/bladewind[v0.1.7].
    - mkocansey/bladewind v0.1.7 requires laravel/framework ^9.0 -> found laravel/framework[v9.0.0-beta.1, ..., 9.x-dev] but it conflicts with your root composer.json require (^8.75).

**Comment by gkimpson** [comment]
This is for Laravel 9.x only unfortunately

**Comment by Tejas20002** [comment]
Hmmm, okay but you do something or change in composer file can work in the
laravel 8

Please......

**Comment by mkocansey** [comment]
@Tejas20002 I am working on making the components compatible with Laravel 8. Will notify you when this is done

**Comment by mkocansey** [comment]
@Tejas20002 check out this announcement [https://github.com/mkocansey/bladewind/discussions/22](https://github.com/mkocansey/bladewind/discussions/22)
