### ISSUE TITLE
When passing in empty data to a table, not row shows "No data to display"

### ISSUE THREAD

**Issue by HarriFent** [mkocansey/bladewind#199]
I have noticed that, when passing my data into the table, if I have no rows in the data, it just doesn't display the table.
I would like it to display a "No data" message in a row, if possible.
I know the headings are generated by the data passed in. So I am not expecting headings.
But a simple "No data available" or even a message to pass in would be nice.

Thank you
Harrison

**Comment by mkocansey** [comment]
@HarriFent Ah!.. this totally escaped me. Definitely a needed enhancement.

**Comment by mkocansey** [comment]
@HarriFent Here you go https://bladewindui.com/component/table#nodata

You will need to `composer update`
