### ISSUE TITLE
Modal title not readable using dark theme

### ISSUE THREAD

**Issue by BeBel42** [mkocansey/bladewind#213]
Hi,

I am using bladewing with the dark theme enabled by default.
While it works well, the title does not adapt its text color accordingly

![image](https://github.com/mkocansey/bladewind/assets/64377698/1d619f98-26b6-4ede-9c94-a5bbec0c7cd5)

When I select the title:

![image](https://github.com/mkocansey/bladewind/assets/64377698/b2c56a16-ceac-4af0-b348-097416ac8a63)

**Comment by mkocansey** [comment]
@BeBel42 please confirm if you are on 2.5.2. This was fixed in that version

**Comment by mkocansey** [comment]
![Uploading Screenshot 2024-03-17 at 13.37.31.png…]()

This is from the documentation.

**Comment by BeBel42** [comment]
Hi,
I am truly sorry. I did not saw you response to the previous issue. You are right - I need to update my bladewind. Thank you very much for this

**Comment by BeBel42** [comment]
Indeed, it is fixed. Closing the issue
