### ISSUE TITLE
modal.blade.php   BUG

### ISSUE THREAD

**Issue by hupengtao** [mkocansey/bladewind#220]
![image](https://github.com/mkocansey/bladewind/assets/28591882/66e11d88-f056-440a-aca7-dfc22ee7315e)
You need to clear w-full, otherwise the size attribute will not take effect and will cause full screen in Windows windows.

**Comment by mkocansey** [comment]
Thanks @hupengtao. Will push an update to fix that.

**Comment by mkocansey** [comment]
Can you please post a screenshot of how the modal is currently displayed for you?

**Comment by mkocansey** [comment]
@hupengtao fixed in 2.5.7. 

`composer update`
