### ISSUE TITLE
x-bladewind.modal   Component parameter passing problem

### ISSUE THREAD

**Issue by hupengtao** [mkocansey/bladewind#222]
This is a business scenario  
How to pass the id to showModal() so that the subsequent ok_button_action 
can obtain the id and then pass it to another js function
/**
         * Get the id and use different showModal() according to different ids.
         */
        function decide_Link(){
            const id = getSelectLogo();
            if(id === 'all'){
                //  link_all   I want to pass this id value but it doesn’t seem to be supported.
                showModal('link_all')
            }else{
                // link_single
                showModal('link_single')
            }
        }

 <x-bladewind::modal
            size="small"
            backdrop_can_close="false"
            type="info"
            ok_button_action="link_single()"
            title="{{__('agent.link-config')}}"
            name="link_single">
        {{__('agent.link_single_point')}}
    </x-bladewind::modal>

    <x-bladewind::modal
            size="small"
            backdrop_can_close="false"
            type="info"
            ok_button_action="link_all()"
            title="{{__('agent.link-config')}}"
            name="link_all">
        {{__('agent.link_all_point')}}
    </x-bladewind::modal>

**Comment by mkocansey** [comment]
Hey @hupengtao please throw some more light on the problem. I don't quite seem to understand.

1. You have two modals. One name `link_single` and the other `link_all`.
2. You have a `decide_Link` function that lets you determine which modal to open based on an `id`.
3. Now, I don't understand the part where you want the `id` to be passed to the modal `ok_action_button`. Do you want for example, `link_single` modal to change it's `ok_button_action` based on the `id`?
