### ISSUE TITLE
Bad performance when add this library

### ISSUE THREAD

**Issue by bobimicroweber** [mkocansey/bladewind#229]
Hello, 
some of this package make laravel slow.
Please, see what happening. 
   WARN  Fatal error: Maximum execution time of 60+2 seconds exceeded (terminated) in vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php on line 76.

**Comment by mkocansey** [comment]
Hello @bobimicroweber, It is unclear from the error how the BladewindUI package is causing the performance issue. Can you provide some more information? Probably you could answer the following to give me some more context 

- Did you get the error as soon as you installed the package?
- Does the error go away when you uninstall the package?
- Is there a specific component from the package you tried to use that resulted in the above error?

Thanks
