### ISSUE TITLE
Card not dark in dark mode

### ISSUE THREAD

**Issue by BeBel42** [mkocansey/bladewind#263]
Hi,
![image](https://github.com/mkocansey/bladewind/assets/64377698/8c7ca46c-c594-4622-80ed-2d2a3bf12910)
This is what I get with this code:
```php
	<div class='mt-6'>
		<?php foreach ($children as $child) : ?>
			<div class='dark:text-red-400'>
				<x-bladewind::tag label="pending" color="red" />
				<x-bladewind::card>gg</x-bladewind::card>
				<a :href="{{  route('show.' . $child['type'], [$child['type'] => $child['id']]) }}">
					{{ $child["name"] }}
				</a>
			</div>
		<?php endforeach; ?>
	</div>
```
As you can see, the card is completely white
I am using bladewind v2.5.12, the latest version at the time of writing

Maybe the background color of the tag should be darker, and its text color lighter in dark mode? That would increase readability

**Comment by mkocansey** [comment]
Hello @BeBel42 have you defined your dark mode colours in your `tailwind.config.js` file as d[escribed here](https://github.com/mkocansey/bladewind/issues/212)

**Comment by BeBel42** [comment]
> Hello @BeBel42 have you defined your dark mode colours in your `tailwind.config.js` file as d[escribed here](https://github.com/mkocansey/bladewind/issues/212)

Pretty much, yes. Here is how it looks:

```javascript
import forms from "@tailwindcss/forms";
import colors from "tailwindcss/colors";

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
    ],
    darkMode: "selector",
    theme: {
        extend: {
            colors: {
                primary: colors.blue,
                secondary: colors.slate,
                green: colors.emerald,
                dark: colors.slate,
                success: colors.emerald,
                error: colors.red,
                warning: colors.amber,
                info: colors.blue,
            },
        },
    },
    plugins: [forms],
};

```

**Comment by mkocansey** [comment]
Code looks good. 
I'll look into why the card isn't working in dark mode. Do other BladewindUI components display properly in dark mode for you though?

**Comment by mkocansey** [comment]
Thanks for the detailed feedback. Very much appreciated. 

Strange that `darkMode: selector` didn't work for you because that's what I use in the BladewindUI docs website. 

I'm glad though that good 'ol `darkMode: class` worked.

I'll look into the datepicker.

**Comment by BeBel42** [comment]
I'm reporting the same issue with dropmenu:
![image](https://github.com/mkocansey/bladewind/assets/64377698/8fa7735a-9313-4384-95d8-85fb431c6e63)

```html
<div class="text-center pb-5 ps-5">
	<x-bladewind::dropmenu trigger_css='text-white' trigger="ellipsis-vertical-icon">
		<x-bladewind::dropmenu-item icon='pencil'>
			<div class='dark:text-red-400'>Edit</div>
		</x-bladewind::dropmenu-item>
		<x-bladewind::dropmenu-item icon='x-mark'>
			Delete
		</x-bladewind::dropmenu-item>
	</x-bladewind::dropmenu>
</div>

```
