### ISSUE TITLE
I turned off dark mode using select component Causes problems with select component color How can I customize the text-color inside

### ISSUE THREAD

**Issue by hupengtao** [mkocansey/bladewind#264]
![image](https://github.com/mkocansey/bladewind/assets/28591882/99f67209-9c0c-42a2-956f-e45f731335d1)
![image](https://github.com/mkocansey/bladewind/assets/28591882/31587ef9-0ab8-4a8c-be64-1ff0142fb910)

**Comment by mkocansey** [comment]
@hupengtao I noticed this also from the last issue raised. This is fixed and a new release will be made available end of this week.

**Comment by hupengtao** [comment]
> @hupengtao我从上次提出的问题中也注意到了这一点。该问题已修复，新版本将于本周末发布。
How do I update this package you updated using composer update?

**Comment by mkocansey** [comment]
I'm sorry I don't understand @hupengtao

**Comment by mkocansey** [comment]
> > @hupengtao我从上次提出的问题中也注意到了这一点。该问题已修复，新版本将于本周末发布。
> 
> How do I update this package you updated using composer update?
> 
> 

I'm sorry I don't understand @hupengtao

**Comment by mkocansey** [comment]
@hupengtao .. The fixes will be available via composer on Friday.

**Comment by hupengtao** [comment]
> @hupengtao.. 修复程序将于周五通过 Composer 提供。

Haven't seen the update yet
