### ISSUE TITLE
As long as the Input component is out of black mode, there will be problems with its css. And the style cannot be modified

### ISSUE THREAD

**Issue by hupengtao** [mkocansey/bladewind#265]
![image](https://github.com/mkocansey/bladewind/assets/28591882/6393eafc-58f6-4c27-b40b-5475b30bf4c9)
![image](https://github.com/mkocansey/bladewind/assets/28591882/659e9c3b-9363-4d20-a084-aba40aa3c79b)

**Comment by mkocansey** [comment]
@hupengtao a fix for this will be released tomorrow

**Comment by hupengtao** [comment]
Has it been updated? I don’t see the version number updated.

**Comment by mkocansey** [comment]
@hupengtao apologies. Run into a crazy bug that delayed the release. `composer update` to get the new update now.
