### ISSUE TITLE
Make required select component non-clearable

### ISSUE THREAD

**Issue by BeBel42** [mkocansey/bladewind#266]
Hi,

When using the select component, there is a little cross icon that allows us to clear the selected value.

While that is useful, that is a useless button to have when the field is required.

Is there a way that required select components can be exempt of that clear button?

![image](https://github.com/mkocansey/bladewind/assets/64377698/ca94634e-91d0-4391-8c22-d497b459077c)

It is not really visible here, but those are the colors of the dark theme.

**Comment by mkocansey** [comment]
You make a valid point @BeBel42. Will add this to the next update.
