### ISSUE TITLE
Required manual select components do not expand

### ISSUE THREAD

**Issue by BeBel42** [mkocansey/bladewind#267]
Hi,

I have copied-pasted the manual select component into my code.

Adding `required="true"` to it prevents it to expand.

```html
<x-bladewind::select name="gender" placeholder="Select Gender" data="manual">
     <x-bladewind::select-item label="Male" value="male" />
     <x-bladewind::select-item label="Female" value="female" />
     <x-bladewind::select-item label="Prefer not to say" value="other" />
</x-bladewind::select>
<x-bladewind::select name="gender" required="true" placeholder="Select Gender" data="manual">
     <x-bladewind::select-item label="Male" value="male" />
     <x-bladewind::select-item label="Female" value="female" />
     <x-bladewind::select-item label="Prefer not to say" value="other" />
</x-bladewind::select>
```

The first one works, the second does not.

Any way to fix this?

**Comment by mkocansey** [comment]
@BeBel42
If you have two selects with the same name in the same page, the second will not work. 

However, if you only provided the two select codes to make your point, I'll look into this and fix.

**Comment by mkocansey** [comment]
@BeBel42 Can you try making this dynamic let me know if it works?

```php
<?php
$gender = [
    [ 'label' => 'Male','value' => 'male' ],
    [ 'label' => 'Female','value' => 'female' ],
    [ 'label' => 'Prefer not to say',       'value' => 'other' ],
];
?>
```

```html
<x-bladewind::select name="gender" :data="$gender" />
```

**Comment by BeBel42** [comment]
Hi,

I apologize. The two names being the same was indeed the issue.

So it's a mistake on my part for this one :sweat: 

I'll close the issue. Again, sorry for the false alert.
