### ISSUE TITLE
DATE PICKER

### ISSUE THREAD

**Issue by resujentoezequiel** [mkocansey/bladewind#274]
Good day,

I encountered an error in the date picker component; the date picker shows more dates than only the selected month.

![image](https://github.com/mkocansey/bladewind/assets/43774016/26340cb3-ef23-42ee-bfb8-d109a5c069cb)

This is my code:

![image](https://github.com/mkocansey/bladewind/assets/43774016/55d85cc7-9b68-45d2-a9ea-2fdfe364a1a2)

Thank you

**Comment by mkocansey** [comment]
Now this is a strange one. 
Your code is absolutely correct. 
Thanks @resujentoezequiel for bringing this up. I'll look into this.

**Comment by mkocansey** [comment]
@resujentoezequiel I cannot seem to reproduce this error. Possible to remove bladewind and reinstall so we see if the problem fixes itself somehow. 😊

**Comment by resujentoezequiel** [comment]
After I reinstalled the Bladewind library, the error or bug still appeared.

The tool versions I use are:
PHP - 8.2
Laravel - 11.8
Bladewind - 2.5.13

**Comment by mkocansey** [comment]
Okay. I will still try to reproduce this from my end.

**Comment by mkocansey** [comment]
@resujentoezequiel are you using other Javascript libraries apart from Alpine.js? Did some reading around and it appears other JS libraries can cause Alpine to reinitialise, resulting in components displaying twice.

**Comment by mkocansey** [comment]
Tried several permutations but just can't seem to reproduce this behaviour.

**Comment by Britishexchangestudent** [comment]
I got this issue and it occured when i added alpine js myself from the website to my <head>, once i removed it, it was fine.

<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.1/dist/cdn.min.js"></script>
