### ISSUE TITLE
Set the date default value from javascript

### ISSUE THREAD

**Issue by resujentoezequiel** [mkocansey/bladewind#275]
Good day,

How can I set a value from javascript to the bladewind date picker? Because .value function is not working.

![image](https://github.com/mkocansey/bladewind/assets/43774016/f0ce5222-d4c0-47e2-9613-9fb6869c0994)

Thank you

**Comment by mkocansey** [comment]
@resujentoezequiel I just added a JS function to the `helper.js` file for this. Will be available in the next update but you can follow the steps below to have it working for you now.

1. Add the function below to your _**project_root > public > vendor > bladewind > js > helpers.js**_
```js
/**
 * Set the value of a datepicker
 * @return {void}
 * @param {string} el_name - name of the input field to update
 * @param {string} date - new value to set
 */
var setDatepickerValue = (el_name, date) => {
    let newValue = date;
    let input = domEl(`.${el_name}`);
    if (!input) {
        console.error(`No datepicker found with the name ${el_name}`);
        return;
    }
    if (!input._x_model) {
        console.error(`Alpine.js component not found for element ${el_name}`);
        return;
    }
    input._x_model.set(date);
}
```

2. Define any datepicker but make sure to give it a name

```html
<x-bladewind::datepicker name="invoice_date" />
```

3. Set the value of the datepicker via Javascript

```js
document.addEventListener('DOMContentLoaded', () => {
   setDatepickerValue('invoice_date', '2020-10-10');
});
```

The function expects the DOM content to have fully loaded to work. Ideally the DOM content should have fully loaded when you decide to call the function later on in your page but if you are testing with `console.log`, you will need to use the event listener as I have done in point 3.

Please let me know if this worked for you.

**Comment by resujentoezequiel** [comment]
Still not working even though I added the code you gave in helper.js

![image](https://github.com/mkocansey/bladewind/assets/43774016/f7769653-9402-4d21-8b09-52d0d844e32e)

![image](https://github.com/mkocansey/bladewind/assets/43774016/43b70cf9-69ea-4384-81d2-b7eecceee945)

![image](https://github.com/mkocansey/bladewind/assets/43774016/52d7c398-6b9e-4b6b-952f-c7aed8e0a85c)

**Comment by resujentoezequiel** [comment]
It's working.

I removed the 
**document.addEventListener('DOMContentLoaded', () => {
});**

**Comment by mkocansey** [comment]
Awesome
