### ISSUE TITLE
Icons don't display when using  dot syntax

### ISSUE THREAD

**Issue by brianmcaudill** [mkocansey/bladewind#276]
How to reproduce:
Run this to set up dot syntax
php artisan vendor:publish --provider="Mkocansey\Bladewind\BladewindServiceProvider" --tag=bladewind-components --force

Add a button to the code using the dot syntax and include an icon
                    <x-bladewind.button
                        radius="full"
                        outline="true"
                        color="blue"
                        name="btn-edit"
                        icon="pencil-square"
                        icon_right="false"
                        >
                        Edit
                    </x-bladewind.button>

This will cause the button text as well as 'component.icon' to be printed as the button text.
Example:
Edit component.icon

**Comment by mkocansey** [comment]
Hello @brianmcaudill I just followed your steps above to reproduce the error but I get the button displayed as it should. 

```html
<x-bladewind.button 
      radius="full"
      outline="true"
      color="blue"
      name="btn-edit"
      icon="pencil-square">Edit</x-bladewind.button>
```

Below is what I get. Are you using `v2.5.13`?

![Screenshot 2024-05-30 at 10 37 18](https://github.com/mkocansey/bladewind/assets/1946332/963dfab4-9f24-40e6-af04-5eb02eba7bda)

**Comment by mkocansey** [comment]
Also, can you check/confirm if you have `icon.blade.php` in your `resources > views > components > bladewind` directory.

**Comment by mkocansey** [comment]
@brianmcaudill is this working for you now?

**Comment by brianmcaudill** [comment]
Yes it is working now. Thank you.
