### ISSUE TITLE
question: How to display form errors

### ISSUE THREAD

**Issue by rabol** [mkocansey/bladewind#29]
Hi

First of all, thanks for the great library !

It would be cool if each input had a build in way to display errors when the input is required or if the validation fails

**Comment by mkocansey** [comment]
Hey @rabol that is a great question/suggestion. I just bumped into the same problem on a project I am working on now. 
![Screenshot 2022-06-06 at 14 40 43](https://user-images.githubusercontent.com/1946332/172183841-453aca4f-d8ea-4a1a-97a2-d9725183f4f6.png)

I am working to include this feature now. Should be done in a day or two.

**Comment by mkocansey** [comment]
@rabol this feature is now available in the latest version of Bladewind. The documentation for the feature is [available here](https://bladewindui.com/component/textbox#validate).
