### ISSUE TITLE
Form fields should respect  <fieldset disabled>

### ISSUE THREAD

**Issue by jaguarman** [mkocansey/bladewind#291]
### current situation:

- there is a set of form fields, like x-bladewind::input and x-bladewind::select
- to reuse these inputs in show.blade and edit.blade HTML allows to wrap them with a <fieldset disabled> statement.
- x-bladewind::input works as expected i.e. input is disabled
- x-bladewind::select does not work as expected, i.e. you still can select values

### wanted situation:
- there is a set of form fields, like x-bladewind::input and x-bladewind::select
- to reuse these inpust from show.blade and edit.blade HTML allows to wrap them with a <fieldset disabled> statement.
- x-bladewind::input works as expected i.e. input is disabled
- x-bladewind::select works as expected i.e. select is disabled

### system
- bladewind V2.6.3
- laravel 11

**Comment by mkocansey** [comment]
@jaguarman if I understand you correctly...

Assuming you have the code below

```
<fieldset disabled="disabled">
     <x-bladewind::input name="first_name" />
</fieldset>
```

Should the `<x-bladewind::input name="first_name" />` be disabled even though a `disabled` attribute has not been specified on it?

**Comment by jaguarman** [comment]
Hi Mike, I'm Peter ;-)
yes, that's the intension of a fieldset.
Currently I'm using a workarround: disabling every single field. Works too, so I think this issue has low priority. 

I'll write down one or two more minimalistic bugs I found.

Best regards
Peter

**Comment by jaguarman** [comment]
>> I'll write down one or two more minimalistic bugs I found.

I know how annoying it is to copy text from an email into a bug ticket system, copy attachments, too, so, if you don't mind, I'll raise issues here on github, so you can plan them in your kanban issue board.

**Comment by mkocansey** [comment]
Hey Peter lol. 
Yes raising issues here work super. 
Will add the solution to this issue to the next release.

**Comment by mkocansey** [comment]
@jaguarman under the hood, Bladewind uses the HTML input for the `x-bladewind::input` that is how come it respects the disabled fields. The `x-bladewind::select` is a custom designed dropdown using DIVs. It'll take a lot of work to get this to respect the disabled fieldset. Unfortunately you will need to set the `disabled="true"` on the select to make it disabled in the disabled fieldset.

```html
<fieldset disabled>
    <x-bladewind::input placeholder="name" />
    <x-bladewind::select disabled="true">
        ...
    </x-bladewind>
</fieldset>
```

**Comment by jaguarman** [comment]
Hi Mike , No problem. It was just a suggestion. There are more important issues and features to fix or implement. Thanks for your kind response.
