### ISSUE TITLE
disabled input and select

### ISSUE THREAD

**Issue by jaguarman** [mkocansey/bladewind#293]
in my show.blade.php I want to show the associated values of a database record.
As you can see in the screenshot, there a 3 different ways a disabled element is shown.

1) <x-bladewind::input label="{{ __('Name') }}" disabled="true" selected_value="{{ $client->name }}" name="name" required="true" />
It's not clear for the user wether the input is disabled or not. 
2) <x-bladewind::select :data="$sectors" label="{{ __('Branche') }}" disabled="true" selected_value="{{ $client->sector_id }}" ....
very poor readability (wrote that already in E-Mail)
3) <x-bladewind::input type="numeric" label="{{ __('Umsatz') }}" disabled="true" selected_value="{{ $client->volume }}" ....
good readability, gray background clearly says: "no input here". That's very good.

I would wish all baldewind inputs/selects would behave like that ;-)

![bladewind disabled](https://github.com/mkocansey/bladewind/assets/23614857/3cf6e02b-a919-4e42-9911-5f0f044c8775)

**Comment by mkocansey** [comment]
The styling needs to definitely be consistent. Thanks @jaguarman for bringing this up.
