### ISSUE TITLE
table component should have a scroll bar when too many rows 

### ISSUE THREAD

**Issue by jaguarman** [mkocansey/bladewind#294]
Hi bladewind team,

I'm building a role-has-permission-form and using the table component instead of select component for a reason: a role can have many permissions and with the ordinary select component I'm missing clarity when selecting many permissions.

The table component comes in handy but, when picking from a large number of permissions, the table becomes very large in height. A slider would be a perfect solution.

What do you think? I'd like to see my post as a feature request.
Thank you.
Best regards from Germany
Peter
![bladewind-table-slider](https://github.com/mkocansey/bladewind/assets/23614857/b8100ff1-2c9c-4412-ae89-6b5dd0feb701)

**Comment by mkocansey** [comment]
Hello @jaguarman can you run me through how a slider like this will work? That will determine if this qualifies as a component for all or very specific to your project needs. 

What will the slider control. The number of rows to display? If you have a screenshot of how this currently looks you can also share. Probably will have an idea about how to implement it differently.

**Comment by jaguarman** [comment]
I used the wrong name. I looked it up, it's called a scroll bar. sorry for that.

implementation could be something like this:

```
<x-bladewind::card>
    <x-bladewind::table 
        :data="$permissions" 
        name="role_x_permissions" 
        selectable="true" checkable="true" 
        divider="thin" />
        max_rows = "6"
    </x-bladewind::card>

```

**Comment by mkocansey** [comment]
Ok @jaguarman the picture makes this clearer. This is very project specific and not the behavior of a table. You'll need to wrap the table in a div that can scroll like shown below. 

```
<x-bladewind::card class="overflow-y-scroll h-96">
    <x-bladewind::table 
        :data="$permissions" 
        name="role_x_permissions" 
        selectable="true" checkable="true" 
        divider="thin" />
        max_rows = "6"
    </x-bladewind::card>
```

From the above code, I added the restriction on the card component. I set the height to `h-96` (you can increase or decrease the values to match your preferred height). When the content of the card grows past the height defined (h-96), a scrollbar will be displayed (overflow-y-scroll).

**Comment by mkocansey** [comment]
> Ok @jaguarman the picture makes this clearer. This is very project specific and not the behavior of a table. You'll need to wrap the table in a div that can scroll like shown below. 
> 
> ```
> <x-bladewind::card class="overflow-y-scroll h-96">
>     <x-bladewind::table 
>         :data="$permissions" 
>         name="role_x_permissions" 
>         selectable="true" checkable="true" 
>         divider="thin" />
>         max_rows = "6"
>     </x-bladewind::card>
> ```
> 
> From the above code, I added the restriction on the card component. I set the height to `h-96` (you can increase or decrease the values to match your preferred height). When the content of the card grows past the height defined (h-96), a scrollbar will be displayed (overflow-y-scroll). 

@jaguarman Did the above solution work for you?

**Comment by jaguarman** [comment]
Michael,

thank you very much for your help and interest.
I'm so sorry but I really had no time as I'm preparing my tax declaration.

I will give you a qualified response as soon as possible.

best regards
Peter





Am Mi., 10. Juli 2024 um 02:21 Uhr schrieb Michael K. Ocansey <
***@***.***>:
