### ISSUE TITLE
table component should use selected value

### ISSUE THREAD

**Issue by jaguarman** [mkocansey/bladewind#295]
when using the table component with checkboxes, it should be possible to load data and use a selected value property.

like this

### controller:
```
public function edit(string $id)
    {
        $role = Role::findOrFail($id);
        $permissions = Permission::orderBy('name')->get(['id','name']);   // all possible permissions
        $role_permissions = '2,3,6';  // selected permissions, I tried all variants below
//        $role_permissions = [2,3,6];
//        $role_permissions = [ 0 => 2, 1 => 3, 2 => 6 ];
//        $role_permissions = [ 0 => '2', 1 => '3', 2 => '6' ];
        return view('roles.edit', [
            'role' => $role,
            'permissions' => $permissions,
            'role_permissions' => $role_permissions,
        ]);
    }
```
 
### blade:

`  <x-bladewind::card>
                            <x-bladewind::table :data="$permissions" selected_value="{{ $role_permissions }}" name="role_permissions" selectable="true" checkable="true" divider="thin" />
                        </x-bladewind::card>`

would be good to have a **selected_value** or **checked_value** property.

**Comment by mkocansey** [comment]
This is a good catch @jaguarman. It was a complete oversight. I’ll add this in the next update.
