### ISSUE TITLE
Select component - doesn't show selected value when readonly

### ISSUE THREAD

**Issue by jaguarman** [mkocansey/bladewind#299]
Hi Bladewind team,

I experienced the following situation:

There is a view with a field "company". Depending on the user permission the following line in the blade is used to show the content of the field "company"

` <div class="sm:col-span-3"><x-bladewind::select :data="$companies" readonly="true" selected_value="{{ $user_company }}" label="{{ __('Company') }}" placeholder="{{ __('Company') }}" name="company" required="true" label_key="name" value_key="id" searchable="true"  show_filter_icon="true" /></div>`

When removing the readonly attribute the content is shown.

Btw, what is the intended different behavior between readonly and disabled for the select component.
Again, thank you for all these marvelous components.

Best regards
Peter

**Comment by mkocansey** [comment]
@jaguarman thanks for bringing this to my attention. Will include the fix in the next update. 

To answer your question about the intended differences between readonly and disabled. The intention is to mimic how HTML treats these attributes for form elements.

	1.	Editable State:
	•	readonly: The user cannot modify the value of the input field, but they can still interact with it (e.g., they can focus on it and copy its content).
	•	disabled: The user cannot interact with the input field at all. It won’t be part of the form submission.
	2.	Form Submission:
	•	readonly: The value of the input field will be submitted with the form.
	•	disabled: The value of the input field will not be submitted with the form.
	3.	Styling:
	•	readonly: The default styling of the input field remains unchanged.
	•	disabled: The input field is usually styled differently (e.g., grayed out) to indicate it is inactive.


BladewindUI Select component does not enforce all of the above. Just a few.
