### ISSUE TITLE
Laravel breeze and Bladewind does not play well

### ISSUE THREAD

**Issue by rabol** [mkocansey/bladewind#30]
Hi 

I have noticed that bladewind changes the css for navigation

after installing bladewind, the menu dropdown is not displaying as before

**Comment by rabol** [comment]
Yes if I remove Bladewind, all looks 'normal'


this is my <head>
```
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>

        <link href="{{ asset('bladewind/css/animate.min.css') }}" rel="stylesheet" />

        <link href="{{ asset('bladewind/css/bladewind-ui.min.css') }}" rel="stylesheet" />

        <script src="{{ asset('bladewind/js/helpers.js') }}"></script>
        <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    </head>
```


It's very easy to reproduce

1) create a new laravel app
2) composer require larave/breeze
3) npm install
4) npm run dev
5) register a new user and observe that you have a simple dropdown
6) install bladewind
7) observe that the 'dropdown' is now a 'hamburger' and when clicked, then menu now fill the whole screen

**Comment by mkocansey** [comment]
Try flipping the positions of your `app.css` and `app.js`. Kindly, place them after the lines for Bladewind like so and let me know if that solved your issue.. 
```
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link href="{{ asset('bladewind/css/animate.min.css') }}" rel="stylesheet" />

        <link href="{{ asset('bladewind/css/bladewind-ui.min.css') }}" rel="stylesheet" />

        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('bladewind/js/helpers.js') }}"></script>

        <script src="{{ asset('js/app.js') }}" defer></script>

        <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
    </head>

**Comment by mkocansey** [comment]
@rabol 
I replicated your steps but Bladewind did not interfere with Breeze at all. 
You can see from the screenshot below, I integrated the Bladewind Horizontal Line Graph on the Breeze Dashboard.

![Screenshot 2022-06-12 at 20 53 50](https://user-images.githubusercontent.com/1946332/173253244-d1d9b42b-68fe-4ec4-98ea-2b7c2ca66da0.png)

When I resize the browser window to mobile size, I get a hamburger which again looks very fine to me. No interference from Bladewind in any way here too.

![Screenshot 2022-06-12 at 20 54 10](https://user-images.githubusercontent.com/1946332/173253314-b01d3165-bb7c-4ad8-9412-743e224fe2fd.png)
