### ISSUE TITLE
Validation not recognizing empty string when containing a space character

### ISSUE THREAD

**Issue by jaguarman** [mkocansey/bladewind#308]
Client-Side validation works fine (big thank you for that!) with one exception:

If you enter an empty string then validation is positive in the sense of OK, but this empty string is passed to the backend and recognized as empty which leads to an error message. Would be great, if strings only containing spaces, carriage return, tabs and line feeds would be considered as empty.
Thank you.

**Comment by mkocansey** [comment]
Very true. I’d fix and push an update.
