### ISSUE TITLE
Minor squirks around the select component

### ISSUE THREAD

**Issue by jaguarman** [mkocansey/bladewind#309]
There is a form with 3 single select components, as shown in the picture.

case 1:
Form is in edit mode, required=false, the selected value is shown, there's no direct possibility to empty the input field.
the workaround is shown in case 2.

case 2:
(required=false) after a new value is selected, the EMPTY-button appears and you can empty the input field.

case 3:
If the field is set to required=TRUE the EMPTY-Button is NEVER shown.

Best regards
Peter

**Comment by mkocansey** [comment]
Hello @jaguarman I believe you forgot to attach the picture.

**Comment by jaguarman** [comment]
Mistakes happen ;-)
Sorry for that. Here you go

![select component](https://github.com/user-attachments/assets/3c55fa8f-598e-45d8-80c4-6d675e0cb72a)

**Comment by mkocansey** [comment]
@jaguarman the reset button should actually only be shown when the field is required. So case 1 and 2 are bugs. Adding to fixes

**Comment by jaguarman** [comment]
Mike, how do you reset the value of a select if the field is not required?
Did I get you wrong?


Michael K. Ocansey ***@***.***> schrieb am Mi., 7. Aug. 2024,
20:58:

**Comment by mkocansey** [comment]
@jaguarman If the select field is not required, the reset icon shows anytime a user selects a value. This way they can click to reset.
