### ISSUE TITLE
input / textarea components don't respect readonly=false but select components do

### ISSUE THREAD

**Issue by jaguarman** [mkocansey/bladewind#310]
I am reusing my form element (INPUT, SELECT, TEXTAREA...) in 3 forms for CREATE, SHOW and EDIT.

Controller has a property READONLY that is TRUE or FALSE and given to the view.
   ```
  // CONTROLLER
     $this->paramReadonly = FALSE;

...
     return view('companies.edit', [
                ...
                'paramReadonly' => $this->paramReadonly,
            ]);

```

IF READONLY is TRUE all elements are readonly. That is correct.
IF READONLY is FALSE then INPUT and TEXTAREA still are READONLY. The others work fine.

Please see picture attached.

Thank you for fixing this.
Best regards
Peter

![readonly - input and textarea](https://github.com/user-attachments/assets/f5fd9561-f16b-4f1e-9762-51fc8ad67900)

```

        <div class="sm:col-span-3"> 
            <x-bladewind::input 
                label="{{ __('Name') }}" 
                selected_value="{{ $company->name }}" 
                name="name" 
                readonly="{{ $paramReadonly }}" 
                required="true" 
                error_message="Gib einen Firmennamen an."
                show_error_inline="true"
            /> 
        </div>

        <div class="sm:col-span-3">
                <x-bladewind::select 
                    :data="$clients" 
                    label="{{ __('Mandant') }}" 
                    selected_value="{{ $company->client_id }}" 
                    name="client" 
                    label_key="name" 
                    value_key="id" 
                    searchable="true"
                    readonly="{{ $paramReadonly }}" 
                    show_filter_icon="true" 
                    required="true" 
                    error_message="Wähle einen Mandanten."
                    show_error_inline="true"
                    />
        </div>
        <div class="sm:col-span-3">
            <x-bladewind::select 
            :data="$sectors" 
            multiple="true"
            label="{{ __('Branche') }}" 
            selected_value="{{ $company->sector_id }}" 
            name="sector" 
            readonly="{{ $paramReadonly }}" 
            label_key="name" 
            value_key="id" 
            searchable="true"
            show_filter_icon="true" 
            />
        </div>


        <div class="sm:col-span-3"> 
            <x-bladewind::textarea 
                label="{{ __('Zusätzliche Beschreibung') }}" 
                placeholder="{{ __('Zusätzliche Beschreibung') }}" 
                name="description" 
                rows="8" 
                selected_value="{{ $company->name }}" 
                readonly="{{ $paramReadonly }}" 
            /> 
        </div>


```

**Comment by mkocansey** [comment]
Hello @jaguarman you will notice the BladewindUI docs for Input and Textarea doesn't list `readonly` as one of the attributes it accepts. That is because BladewindUI uses the standard HTML controls for its textarea and input. In HTML, the control is made `readonly` when the attribute is present not based on its value. So all these will make an input readonly in standard HTML, `readonly="true", readonly="yes", readonly="false", readonly="mike" `. 

The only way to **not** make the field readonly is to leave out the attribute entirely. Hope this helps.

**Comment by jaguarman** [comment]
Sure I can change it, but I had hoped the syntax would be more consistent. 
Anyway, thank you for pointing this out. So. please close this issue.

**Comment by jaguarman** [comment]
mmmhhh, not so easy to change

tried this:

CONTROLLER
`$paramReadonly = 'readonly="true"'  or $paramReadonly = ' '`

BLADE
```
 <x-bladewind::input 
                label="{{ __('Name') }}" 
                selected_value="{{ $company->name }}" 
                name="name" 
                {{ $paramReadonly }}
            /> 

```

no bladewind component is shown as a result.

**Comment by jaguarman** [comment]
tried this, also with no positive result, which means bladewind component doesn't show up as well

CONTROLLER
`$paramReadonly = TRUE  or $paramReadonly = FALSE`

BLADE

            <x-bladewind::input 
                label="{{ __('Name') }}" 
                selected_value="{{ $company->name }}" 
                name="name" 
                @if ($paramReadonly === TRUE ) 
                    readonly="true" 
                @endif
            />

**Comment by jaguarman** [comment]
this works, but duplicates code

  @if ($paramReadonly == TRUE ) 
            <x-bladewind::input 
                label="{{ __('Name') }}" 
                selected_value="{{ $company->name }}" 
                name="name" 
                readonly="true" 
                required="true" 
                error_message="Gib einen Firmennamen an."
                show_error_inline="true"
            /> 
            @else
                <x-bladewind::input 
                label="{{ __('Name') }}" 
                selected_value="{{ $company->name }}" 
                name="name" 
                required="true" 
                error_message="Gib einen Firmennamen an."
                show_error_inline="true"
                /> 
            @endif

**Comment by jaguarman** [comment]
do you know any better solution?
TIA

**Comment by mkocansey** [comment]
I haven't tested this but try let me know if it works. 

`$readonly = ($paramReadonly) ? 'readonly="true" ' : '';`

```
<x-bladewind::input 
    label="{{ __('Name') }}" 
    selected_value="{{ $company->name }}" 
    name="name" 
    {{ $readonly }} 
    required="true" 
    error_message="Gib einen Firmennamen an."
    show_error_inline="true"
 />
```

**Comment by jaguarman** [comment]
Oh, didn't see you emailed me.
Tried exactly this, as written in my comment.
Bladewind components disappear completely if used like this.
But this would be of great help.





Am Di., 6. Aug. 2024 um 12:18 Uhr schrieb Michael K. Ocansey <
***@***.***>:

**Comment by mkocansey** [comment]
For convenience, I'll add a readonly attribute to the Input and Textarea components later today and release an update.

**Comment by jaguarman** [comment]
That's very good news.
Thank you, Mike.
Regards
Peter


Michael K. Ocansey ***@***.***> schrieb am Mi., 7. Aug. 2024,
05:49:
