### ISSUE TITLE
Textarea toolbar not sending through value on form submission

### ISSUE THREAD

**Issue by Britishexchangestudent** [mkocansey/bladewind#315]
In my form i have the textarea with the tooltip active and required as true, the textarea input background color is transparent and doesnt have the required star like the select does and when the form is submitted the value isnt passed through. Once i remove 

```
    @if ($toolbar)
        <div id="{{ $name }}">
            {{ $selected_value }}</div>
    @else
```
The textarea works as normal without the tooltip of course and the value is sent through when the form is submitted.

<img width="1478" alt="Screenshot 2024-08-15 at 13 00 58" src="https://github.com/user-attachments/assets/7dbdfb42-7807-4f6b-b020-a7baba287678">

Also there are added inputs being submitted with the form submission, is this supposed to be the case?

<img width="329" alt="Screenshot 2024-08-15 at 13 17 43" src="https://github.com/user-attachments/assets/1627be3b-a4a6-4b44-8765-395ddd3fea73">

Above is what happens when i dd the request after submitting the form

Thanks

**Comment by mkocansey** [comment]
@Britishexchangestudent thanks for bringing this up. I will check and fix. ideally other fields should not be submitted with the textarea.

**Comment by mkocansey** [comment]
@prince-noman 
It will automatically be closed when the code is merged into main
