### ISSUE TITLE
Datepicker doesn't show up

### ISSUE THREAD

**Issue by jaguarman** [mkocansey/bladewind#316]
Hi Mike, 

the datepicker doesn't show up in my blade file.
I narrowed the problem down to an empty blade file with only on element: the datepicker.

I'll add the rendered html output. I found something line "display: none" 

May that be the problem?

Best regards
Peter

[rendered output.txt](https://github.com/user-attachments/files/16731243/rendered.output.txt)

**Comment by mkocansey** [comment]
Hi @jaguarman have you included the alpine.js file. This is required for the datepicker to work?

**Comment by mkocansey** [comment]
`<script src="//unpkg.com/alpinejs" defer></script>`

Should be available on any page that requires the  datepicker.

**Comment by jaguarman** [comment]
Hey Mike,

I hadn't.
Now I have. It works.
Embarrassing.
I beg your pardon.

Have a nice weekend.

best regards
Peter




Am Fr., 23. Aug. 2024 um 18:22 Uhr schrieb Michael K. Ocansey <
***@***.***>:

**Comment by mkocansey** [comment]
No need to be embarrassed. 
Just a hint for me to add that to the datepicker docs. It's currently only mentioned in the installation docs. Thanks. 

Have a nice weekend.
