### ISSUE TITLE
Class !text-center not available in bladewind-ui.min.css

### ISSUE THREAD

**Issue by berrugo** [mkocansey/bladewind#319]
This class allows me to center table headers, just like you do in the docs, but its missing from bladewind-ui.min.css 
@mkocansey I can create a PR that adds this class in the css file in but I suspect this is a generated file.

**Comment by prince-noman** [comment]
@berrugo You are right, that's a minified version of bladewind-ui.css. Thanks for raising this issue. I have added a PR that solves this issue. Hopefully, @mkocansey will merge it very soon.

Thank you.

**Comment by mkocansey** [comment]
Hello gentlemen. You're right. `!text-center` is missing from the bladewindcss file but it's deliberate. In the docs example, `!text-center` is defined in the docs css. Ideally a library should not set classes that cannot be overwritten. 

If a component sets a `!text-center`, you won't be able to overwrite this as a user even with `!text-right`.

**Comment by prince-noman** [comment]
@mkocansey But as !text-left and !text-right are present in the bladewind-ui.min.css so it's expected that !text-center should be there.

**Comment by mkocansey** [comment]
@prince-noman you make a good point. In that case you will need to add `!text-center` to the `'text' =>   ''` key in the `compile-for-tailwind.blade.php` file and not the minified css file. Please do this and resubmit a PR

**Comment by prince-noman** [comment]
@mkocansey Ok, thank you for your suggestion. I will do it within a few moments.

**Comment by prince-noman** [comment]
@mkocansey I have submitted PR #321.

**Comment by berrugo** [comment]
Thank you @mkocansey and @prince-noman
