### ISSUE TITLE
How am I supposed to align this?

### ISSUE THREAD

**Issue by Visnicio** [mkocansey/bladewind#323]
I have this simple setup
```html
  <div class="grid grid-cols-12 items-end mb-6">
        <div class="col-span-9">
            <x-bladewind::input id="search" class="!mb-0"/>
        </div>
        <div class="col-span-3">
            <x-bladewind::button id="search-button">Pesquisar</x-bladewind::button>
        </div>
    </div>
```

But I simply cannot align it, the default input has some margin-bottom that I cannot change
![image](https://github.com/user-attachments/assets/b572358c-ca0f-4b7a-8b90-ad0e6a29d450)

![image](https://github.com/user-attachments/assets/5e65c1a9-5dab-4814-a480-6cbf6c49ec49)

I know I can change the source code of the component, but I dont like this approach, is there any other way?

It would be nice if the library accepted an additional class attribute
like some other libraries do
`<x-bladewind::input class="mb-0">`

**Comment by mkocansey** [comment]
Hey @Visnicio you actually have two options

`<x-bladewind::input add_clearing="false">`

or 

`<x-bladewind::input class="!mb-0">`

**Comment by Visnicio** [comment]
hey @mkocansey 
the `add_clearing="false"` attr worked for me, thanks!

tho the !mb-0 didn't as it was my first try :(

I think that it would be nice to test some components with the class attribute, cause there are a lot of components where some behaviors are not desired, but changing the class attr does nothing, since it targets the wrong element

I got in another situation where I need to a modal overflow the screen, it's a edit modal and there's is a lot of info inside it, but most of the modal stays hidden under the screen

**Comment by Visnicio** [comment]
![image](https://github.com/user-attachments/assets/a429f946-3ee2-4f44-a34a-5e48a59c7092)
As the time of testing, the modal component simply doesn't accept the class attribute somehow

**Comment by mkocansey** [comment]
@Visnicio What you need to set is the `body_css` attribute. Not css. All these are defined in the docs under **Full List of Attributes**__

**Comment by Visnicio** [comment]
Reading the docs, my biggest fear 

Thanks brother, Im currently not in my office but I will check it out
