### ISSUE TITLE
Icon not showing on selects

### ISSUE THREAD

**Issue by Britishexchangestudent** [mkocansey/bladewind#326]
Icons aren't showing on my selects, do i need to install something else? All icons are showing with the label
![Screenshot 2024-09-10 at 15 02 15](https://github.com/user-attachments/assets/9b130f8d-694a-4f3b-84ae-417d80922b34)

Icons on button is fine
![Screenshot 2024-09-10 at 15 04 46](https://github.com/user-attachments/assets/3dc6c6ff-c66d-40f1-824b-66d8dd1fd515)

**Comment by mkocansey** [comment]
Hey @Britishexchangestudent please paste the code that creates the select you showed above.

**Comment by Britishexchangestudent** [comment]
<div class="relative w-full dv-input_66e1982d9f8ae ">
    <input class="bw-input peer  input_66e1982d9f8ae  medium !border-0 !border-b !rounded-none focus:!border-slate-300 dark:focus:!border-slate-600 !w-full !text-sm bw_search" type="text" id="input_66e1982d9f8ae" name="input_66e1982d9f8ae" value="" autocomplete="new-password" placeholder="Type here..." style="padding-right: 130px;">
                        <div class="input_66e1982d9f8ae-suffix suffix text-sm select-none pl-3.5 !pr-3 rtl:!right-[unset] rtl:!left-0 z-20 text-blue-900/50 dark:text-dark-400 absolute right-0 inset-y-0 inline-flex items-center " data-transparency="1">
                            magnifying-glass
                    </div>
        <script>positionSuffix('input_66e1982d9f8ae');</script>
    </div>

**Comment by Britishexchangestudent** [comment]
`<div class="relative w-full dv-input_66e1982d9f8ae ">
    <input class="bw-input peer  input_66e1982d9f8ae  medium !border-0 !border-b !rounded-none focus:!border-slate-300 dark:focus:!border-slate-600 !w-full !text-sm bw_search" type="text" id="input_66e1982d9f8ae" name="input_66e1982d9f8ae" value="" autocomplete="new-password" placeholder="Type here..." style="padding-right: 130px;">
                        <div class="input_66e1982d9f8ae-suffix suffix text-sm select-none pl-3.5 !pr-3 rtl:!right-[unset] rtl:!left-0 z-20 text-blue-900/50 dark:text-dark-400 absolute right-0 inset-y-0 inline-flex items-center " data-transparency="1">
                            magnifying-glass
                    </div>
        <script>positionSuffix('input_66e1982d9f8ae');</script>
    </div>`

**Comment by Britishexchangestudent** [comment]
> In the meantime can you Check your `project root > public > vendor > bladewind > icons > outline > magnifying-glass.svg` for the file.

yes its there

![Screenshot 2024-09-11 at 14 17 56](https://github.com/user-attachments/assets/304343be-c289-4f52-b1c5-b961fd497212)

**Comment by Britishexchangestudent** [comment]
![Screenshot 2024-09-11 at 14 40 27](https://github.com/user-attachments/assets/a9ffc4b5-fd68-434e-8788-b6e178f7f81b)
yes the icons are there

**Comment by haugen86** [comment]
Can this has something to do with https://bladewindui.com/laravel8-users?

**Comment by Britishexchangestudent** [comment]
> Can this has something to do with https://bladewindui.com/laravel8-users?

Tried it both ways and still same result if i leave it as 'magnifying-glass' but with the svg itself it works

**Comment by Britishexchangestudent** [comment]
When i've merged my branch into master the icon fails to show up again even though the changes are present in the vendor file, do i need to run php artisan vendor:publish --tag=bladewind-public --force to see the changes?

 On master
![Screenshot 2024-09-12 at 15 07 22](https://github.com/user-attachments/assets/d69670e7-ee08-4d11-aaa5-87efa5134ae1)


On Dev branch:
![Screenshot 2024-09-12 at 15 08 09](https://github.com/user-attachments/assets/6da41b4d-4985-4528-b600-08ce7323fd0c)

**Comment by mkocansey** [comment]
Yes. You need to run vendor:publish to move files from the vendor directory to your projects public directory

**Comment by mkocansey** [comment]
> Yes. You need to run vendor:publish to move files from the vendor directory to your projects public directory

@Britishexchangestudent did vendor:publish solve your issue?

**Comment by Britishexchangestudent** [comment]
> > Yes. You need to run vendor:publish to move files from the vendor directory to your projects public directory
> 
> @Britishexchangestudent did vendor:publish solve your issue?

Nope, only things that seem to change it is using the actual svg instead of the name of the icon and changing suffix_is_icon and suffixIconType to true on line 65 in input.blade.php.

![Screenshot 2024-09-16 at 12 44 44](https://github.com/user-attachments/assets/e6f53a1b-d0e4-41c0-b7fe-1ea2fece114f)

**Comment by Britishexchangestudent** [comment]
When i try to debug it, it seems suffix_is_icon isn't being passed through for some reason on my project, but when i create a new project it works? suffix_is_icon shows as 1 for x-mark icon when clearable is true. 

![Screenshot 2024-09-18 at 12 17 14](https://github.com/user-attachments/assets/5811fe28-e42b-4dab-8cfa-3b726f57ad37)

select.blade.php

`        <div
            class="sticky top-0 min-w-full bg-slate-100 dark:bg-transparent py-1 pr-0 -pl-1 @if (!$searchable) hidden @endif">
            <x-bladewind::input
                class="!border-0 !border-b !rounded-none focus:!border-slate-300 dark:focus:!border-slate-600 !w-full !text-sm bw_search"
                add_clearing="false" placeholder="Type here..." suffix="magnifying-glass" suffix_is_icon="true" />
        </div>`


input.blade.php:
` <div class="{{ $name }}-suffix suffix text-sm select-none pl-3.5 !pr-3 {{ $suffix_icon_div_css }} z-20 text-blue-900/50 dark:text-dark-400 absolute right-0 inset-y-0 inline-flex items-center @if (!$transparent_suffix) bg-slate-100 border-2 border-slate-200 border-l-0 dark:border-dark-700 dark:bg-dark-900/50 dark:border-l-0 rounded-tr-md rounded-br-md @endif"
            data-transparency="{{ $transparent_prefix }}">
            <div>
                <p>suffix: {{ $suffix }}</p>
                <p>suffix2: '{!! $suffix !!}'</p>
                <p>suffix_is_icon: {{ $suffix_is_icon }}</p>

            </div>
            @if ($suffix_is_icon)
                <x-bladewind::icon name='{!! $suffix !!}' type="{{ $suffix_icon_type }}"
                    class="!size-4 !stroke-2 !opacity-85 hover:!opacity-100 {{ $suffix_icon_css }}"
                    action="{!! $action !!}" />

                {{-- this will be shown when user clicks to reveal password // so they can hide the password --}}
                @if ($type == 'password' && $viewable)
                    <x-bladewind::icon name='eye-slash' type="{{ $suffix_icon_type }}"
                        class="!size-4 !stroke-2 !opacity-85 hover:!opacity-100 hide-pwd hidden"
                        action="togglePassword('{{ $name }}', 'hide')" />
                @endif
            @else
                {!! $suffix !!}
            @endif
        </div>`
        
        
        using "laravel/framework": "^8.0" on this project, whereas the example project i created to test is running "laravel/framework": "^11.9",

**Comment by mkocansey** [comment]
Thanks @Britishexchangestudent for throwing more light on this. Will try and fix this but no promises especially since support for Laravel 8 is coming to an end in a month or two. Things to do with how Laravel 8 interprets variable names with underscores. 

Can you try this. Create an input field with an  icon and set `suffixIsIcon="true"`. Note how this attribute is defined as camel case.
