### ISSUE TITLE
If an empty data set is sent to the select, it dies with a message that the label value should exist on the data set

### ISSUE THREAD

**Issue by haugen86** [mkocansey/bladewind#335]
I would suggest that the select still shows, but with a message about no selectable values. Also I think using the `die()`  in production isn't the ideal way of handling errors.

I can do a PR for handling the empty array for now, and maybe we can discuss and agree on how failing selects should behave, I think we can come up with a better solution 😄 

How do you feel about that @mkocansey ?

**Comment by mkocansey** [comment]
Hey @haugen86 sounds good. Please do the PR for the empty array. Regarding failing selects, there's a task to display empty states for selects. That should solve the problem.
