### ISSUE TITLE
after upgrade: input component don't respect readonly="false"

### ISSUE THREAD

**Issue by jaguarman** [mkocansey/bladewind#342]
Hi Mike,

I've just upgraded from 2.6.8 to 2.6.9
Now all forms that have been working before no longer do.

all input fields are now readonly, you remember my approad with        
`readonly="{{ $readonly }}" `
even if I change to
`readonly="false"`
the input field still is readonly.

The reason for my upgrade: I wanted to use a textarea and noticed, that it was readonly despite to the fact that it already had worked.
(please see here: https://github.com/mkocansey/bladewind/commit/1858ecef10d8cab8c13332328a6a516844910f39)

the select component still works fine.

Do I have to change some lines in your code as I was told before?

Best regards
Peter

**Comment by mkocansey** [comment]
@jaguarman checking this right away

**Comment by jaguarman** [comment]
Hi Mike, I received a message about a fix, but composer update says:
nothing to install.
What am I doing wrong?
Best regards and thanks for the quick fix.

Peter



Am Sa., 14. Sept. 2024 um 16:40 Uhr schrieb Michael K. Ocansey <
***@***.***>:

**Comment by mkocansey** [comment]
I have committed the fixes but not generated a new version yet. Have a few more tasks to complete for the new release later this week.

**Comment by jaguarman** [comment]
no problem.
I'm happy that you fix it and that bladewind exists.
It's perfect for my needs.

Have a good week
Peter


Am So., 15. Sept. 2024 um 21:56 Uhr schrieb Michael K. Ocansey <
***@***.***>:
