### ISSUE TITLE
<a> styled as a button

### ISSUE THREAD

**Issue by rabol** [mkocansey/bladewind#35]
Hi

Would be nice to have a <a> link styled as a  button :)

**Comment by mkocansey** [comment]
@rabol 
Why don't we just wrap the button in an `<a>` like so 
`<a href="/my/link"><x-bladewind.button>See details</x-bladewind.button></a>`  :)

**Comment by mkocansey** [comment]
@rabol you can do this now in >=v1.1.3

`<x-bladewind.button tag="a">Subscribe Now</x-bladewind.button>`
