### ISSUE TITLE
Select component doesn't work on staging server

### ISSUE THREAD

**Issue by Visnicio** [mkocansey/bladewind#351]
![image](https://github.com/user-attachments/assets/c086dd86-372b-4516-8891-2ba5bfd8c5e0)
I get this problem in my staging server while the same code on my local enviroment (sail) works fine

**Comment by Visnicio** [comment]
found a temporary fix (this project will be in my client's hands tomorrow lol)

![image](https://github.com/user-attachments/assets/f13076ae-8947-495f-a810-ea96201fdc48)
the image above works fine

but as soon as I go to the backend and retrieve the data as `data="{{json_encode($data)}}"` nothing works anymore

**Comment by Visnicio** [comment]
![image](https://github.com/user-attachments/assets/809c2221-3802-443c-8dfe-affc1b3b3add)

**Comment by mkocansey** [comment]
@Visnicio is your staging server running the latest version of BladewindUI?

**Comment by mkocansey** [comment]
> ![image](https://private-user-images.githubusercontent.com/70033167/370081531-809c2221-3802-443c-8dfe-affc1b3b3add.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzA0NDIsIm5iZiI6MTcyNzE3MDE0MiwicGF0aCI6Ii83MDAzMzE2Ny8zNzAwODE1MzEtODA5YzIyMjEtMzgwMi00NDNjLThkZmUtYWZmYzFiM2IzYWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA5MjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZGMyNGQ4MDA0M2UxMjhjYzkwMWUxNTllMmRlZjAwMmU1MWMzMDY3NzBhMmNmNjg3YzM4ZmIwNjBiMWZlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WEZ7BkisfSKD36sGAzg2hLghesZcjvOr9Nq2n0Lzv-s)

@Visnicio is this example you posted your code should either be `:data="$search_options"` or `data="{{ json_encode($search_options)}}"`

**Comment by mkocansey** [comment]
> ![image](https://private-user-images.githubusercontent.com/70033167/370080256-c086dd86-372b-4516-8891-2ba5bfd8c5e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzA3MTksIm5iZiI6MTcyNzE3MDQxOSwicGF0aCI6Ii83MDAzMzE2Ny8zNzAwODAyNTYtYzA4NmRkODYtMzcyYi00NTE2LTg4OTEtMmJhNWJmZDhjNWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA5MzMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZWY3NjI1Mzk0ZTljNTFmNTJiMDBhZDMxYjczNDdmYjY5MjYwY2Q2MTdmODFlMDViMTU4YWIzMzM2ZWEyZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0rfR8cbV_MIvNz9nU1RDx-zd5DoufvIG8F1EV8hj7CQ) I get this problem in my staging server while the same code on my local enviroment (sail) works fine

Please update your version of BladewindUI to the latest. The code from `line 372` was removed in a previous version.

**Comment by Visnicio** [comment]
hey @mkocansey 
Just to make sure we are on the same page....
My controller has a private variable that maintains the search_options for that controller
```php
private $search_options
```

Whenever I need it I would send it as json for the blade file as seen on the third image
```php
...["search_options" => json_encode($search_options)]
```
And from my understanding I could use this on the front end as `data="{{$search_options}}"` no?
What am I missing?

**Comment by mkocansey** [comment]
Hey @Visnicio your approach is correct. Kindly ensure your environments are all using the latest version of BladewindUI.

**Comment by Visnicio** [comment]
Thanks I will update my bladewind version and see what happens, thanks for the good support, as always :)
