### ISSUE TITLE
How to disable dark mode

### ISSUE THREAD

**Issue by hupengtao** [mkocansey/bladewind#352]
I disabled the dark mode in the tailwind.config.js file, but when I use <x-bladewind::filepicker it still shows dark Can you please tell me how to disable the dark mode, because it's very hard to be compatible with my existing components?
![image](https://github.com/user-attachments/assets/36fd9888-3f10-4070-a7fd-ebc0cfaa22cb)
![image](https://github.com/user-attachments/assets/4c2ac066-0c7e-4c7c-9b3c-09970936e4c2)
![image](https://github.com/user-attachments/assets/8bed05e8-79c1-40ca-b9dc-96395f67a04e)

**Comment by mkocansey** [comment]
@hupengtao kindly add `"./vendor/mkocansey/bladewind/resources/views/**/*.blade.php",` to your tailwind config. Also you will need to remove the line `dark: colors.slate`. BladewindUI uses that to determine your darkMode colours. Hope this helps.

**Comment by hupengtao** [comment]
> @hupengtao
> 
> * 请添加`"./vendor/mkocansey/bladewind/resources/views/**/*.blade.php",`到您的 tailwind 配置中。
> * 您还需要删除该行`dark: colors.slate`。BladewindUI 使用它来确定您的 darkMode 颜色。
> * 设置`darkMode: false`不`darkMode: 'false'`
>   希望这会有所帮助。
Changed it based on your response.
Changed from 'false' to false.
It's gone straight to dark mode.
I need to disable dark mode.  
![image](https://github.com/user-attachments/assets/be48240e-0bab-470c-9f24-4032402a4956)
![image](https://github.com/user-attachments/assets/32e153ce-e781-4d99-8861-c78587a80845)

**Comment by hupengtao** [comment]
<x-bladewind::modal
are all capable of disabling dark mode 
But <x-bladewind::filepicker and <x-bladewind::textarea 
can't disable dark mode. It seems to be fixed.

**Comment by mkocansey** [comment]
I’ll take a look at this again and revert.

**Comment by mkocansey** [comment]
@hupengtao I can't seem to replicate this. I turned off dark mode for the bladewindUI docs website and the Filepicker and textarea both respected the settings. Which version of BladewindUI are you on?
