### ISSUE TITLE
Select not responding

### ISSUE THREAD

**Issue by emiku90** [mkocansey/bladewind#353]
I installed BladewindUI on laravel 11 with livewire, alpine and tailwind. After that I tried to use the `<x-bladewind::select />`. 

Every other component seems to be working as it's supposed to, but the select is not clickable at all.  It looks like it is disabled.
The code I'm using is 
`<x-bladewind::select name="customer_id" searchable="true" label_key="name" value_key="id"  :data="$customers" />`

**Comment by mkocansey** [comment]
@emiku90 can you show me the structure of your `$customers` data? Just the structure not necessarily the actual data.

**Comment by emiku90** [comment]
Data is coming from a livewire component ant the structure is

`public function render()
    {
        return view('livewire.tview', [
            'customers' => Customer::all(),
        ]);
    }`

**Comment by fabpl** [comment]
Hi @emiku90,
`Customer::all()` returns a Eloquent Collection, not an array with the expected structure.

https://bladewindui.com/component/select#basic 

```php
$customers = [
    [ 'label' => 'Benin',         'value' => 'bj' ],
    [ 'label' => 'Burkina Faso',  'value' => 'bf' ],
    [ 'label' => 'Ghana',         'value' => 'gh' ],
    [ 'label' => 'Nigeria',       'value' => 'ng' ],
    [ 'label' => 'Kenya',         'value' => 'ke' ]
];
```

**Comment by mkocansey** [comment]
> Hi @emiku90, `Customer::all()` returns a Eloquent Collection, not an array with the expected structure.
> 
> https://bladewindui.com/component/select#basic
> 
> ```
> $customers = [
>     [ 'label' => 'Benin',         'value' => 'bj' ],
>     [ 'label' => 'Burkina Faso',  'value' => 'bf' ],
>     [ 'label' => 'Ghana',         'value' => 'gh' ],
>     [ 'label' => 'Nigeria',       'value' => 'ng' ],
>     [ 'label' => 'Kenya',         'value' => 'ke' ]
> ];
> ```

Hello @fabpl can you try passing `Customer::all()->toArray()` to the component instead of the Eloquent collection? Do let me know if that works for you so I convert all Eloquent collections to arrays by default.
