### ISSUE TITLE
Make repo available for DigitalOceans hacktoberfest?

### ISSUE THREAD

**Issue by haugen86** [mkocansey/bladewind#354]
Would be cool if you could add the repo to DigitalOceans hacktoberfest 😎 I have some PRs I want to submit next week for review 🎸

[participating] Your PR/MRs must be in a repo tagged with the “hacktoberfest” topic, or have the “hacktoberfest-accepted” label.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by mkocansey** [comment]
Sure mate. I’d read up on this in a bit.

**Comment by mkocansey** [comment]
Done ✔️
