### ISSUE TITLE
Input not receiving styles

### ISSUE THREAD

**Issue by Visnicio** [mkocansey/bladewind#363]
I have made the setup as said in the docs, unfortunately something went wrong and some components are not receiving the styles.

![image](https://github.com/user-attachments/assets/a9f92786-8a08-4048-b339-0aa5b6912363)

![image](https://github.com/user-attachments/assets/8a322d01-e88d-4e07-affa-1e42b62d7a22)

**Comment by mkocansey** [comment]
Hey @Visnicio 

Try adding the Bladewind path to your tailwind config js file for compilation

```js
// your-project/tailwind.config.js
module.exports = {
...
  content: [
      ...
      "./vendor/mkocansey/bladewind/resources/views/**/*.blade.php",
  ],
```

If this does not work, you may just need to move the tailwind import before the Bladewind import since that works in your case.

**Comment by Visnicio** [comment]
Hey @mkocansey, thanks for the help

Yeah, I already looked at the docs at thought that putting the bladewind files on my tailwind config would work... but it doesn't :(

Also. Moving my tailwind import before bladewind import breaks my responsiveness, but I'm not quite sure why

Here's a video to show that, hope this helps to identify the problem


https://github.com/user-attachments/assets/9bad248d-5113-4dd6-b034-8a0b162514da

Could be cause i'm using vite for tailwind and asset loading for baldewind?

**Comment by mkocansey** [comment]
@Visnicio Using Vite is not the problem. I use BladewindUI in projects that use Vite for compiling assets. Let me try replicating how your assets are arranged and see if I get any issues.

**Comment by Visnicio** [comment]
it seems a tailwind problem, I'm trying to tweak it with tailwind preflight, but no success until now

https://stackoverflow.com/questions/71783177/remove-specific-style-from-tailwind-base

**Comment by mkocansey** [comment]
@Visnicio I am glad you managed to nail this down. Did turning off preflight work for you?

**Comment by Visnicio** [comment]
Unfortunately no and I dont know why :(

**Comment by mkocansey** [comment]
Is it only the input component that is not receiving styles? Do the other bladewindUI components' styles work as expected?

Also.. thanks for the other alert.

**Comment by mkocansey** [comment]
Do you have a temporal place you can host this for us to possibly debug?

**Comment by Visnicio** [comment]
> Also.. thanks for the other alert.
Don't mention it, its not much for now but hope this helps :)

> Do you have a temporal place you can host this for us to possibly debug?
yeah, I have an staging server for the app, I will update it

you can find it in hml.gametrampo.com.br

**Comment by mkocansey** [comment]
@Visnicio I played around with the page on the url you shared and noticed tailwind is overwriting the input styles in its base. 

Can you comment out this line from your app.scss and let's see if everything works as expected?

```css
/*@tailwind base;*/ /* this line is now commented out */

@tailwind components;

@tailwind utilities;
```

**Comment by Visnicio** [comment]
Hey @mkocansey, thanks for the support!

It worked as intended, I will keep it commented for now since it looks like I use more of the utilities than the base :)

I will close the issue, thanks again and keep the awesome work!

**Comment by mkocansey** [comment]
Awesome. Glad I could help.
