### ISSUE TITLE
Modal not closing when clicking on background

### ISSUE THREAD

**Issue by jaguarman** [mkocansey/bladewind#365]
Hi Mike,

i've been using the modal for some time now and it always worked well.
Been in a different part of my project now for some weeks, came back and noticed that the modal is no longer closing when clicking on the background. This seems to be related to my latest composer update.

that's my code

`<x-bladewind::modal show_action_buttons="false"    show_close_icon="true" size="big" sm:size="XL" blur_size="none" title="Aktions-Menü" name="actionbuttons">
`
this one doesn't work either

`<x-bladewind::modal show_action_buttons="false"   backdrop_can_close="true" show_close_icon="true" size="big" sm:size="XL" blur_size="none" title="Aktions-Menü" name="actionbuttons">`

best regards
Peter

**Comment by mkocansey** [comment]
hey @jaguarman ... I take it you are running v2.7.0? The modal works fine from here and in the docs using the latest version.
Just a quick question though... what is `sm:size="XL"`?

**Comment by jaguarman** [comment]
>  what is sm:size="XL"?
seems to be some kind of typo occurring after midnight ;-)
Will check the modal again and let you know. Thank you

**Comment by jaguarman** [comment]
yes its 2.7.0 and showing the following behaviour:

- does not close when clicking on background
- does not close when pressing ESC button
- have to reload the page

what can be the reason for this?
console shows this: 1:485 Uncaught ReferenceError: dom_el is not defined

regards
Peter

**Comment by mkocansey** [comment]
Hey @jaguarman can you 'inspect element' on your page and send me the entire generated HTML via email?

**Comment by jaguarman** [comment]
Sure, here you go!

I've attached the info.

Regards
Peter


Am Sa., 19. Okt. 2024 um 12:30 Uhr schrieb Michael K. Ocansey <
***@***.***>:

**Comment by mkocansey** [comment]
@jaguarman I am unable to find the attachment ... please send to my email.

**Comment by jaguarman** [comment]
don't have your email address, so I try an upload here.
changed suffix to txt instead of html.
Here you go...
[mike.txt](https://github.com/user-attachments/files/17464271/mike.txt)

**Comment by mkocansey** [comment]
I see the code now. Will take a look and revert.

**Comment by jaguarman** [comment]
same issue (dom_el) plus this one on a simple page with a select:

Uncaught ReferenceError: positionSuffix is not defined

**Comment by mkocansey** [comment]
Please vendor publish and ensure the BladewindUI helper.js is included in your page. Your error suggests the functions from that file cannot be found.

**Comment by jaguarman** [comment]
Hi Mike,
Thanks a lot.
I had comment the helper out, cause it was interfering with some livewire thing, but I don't remember with what.
Have included it again and it works.
Keep you informed if there's still some interference.
best regards
Peter
