### ISSUE TITLE
Searchable Tables with large data sets - performance issues

### ISSUE THREAD

**Issue by ntbutler-nbcs** [mkocansey/bladewind#366]
Greetings.

I've just come across BladewindUI and love the look of it - however I hit a bit of a hurdle when trying to implement my first component into my project. Specifically, I've been looking at a nice way to implement a searchable table for my users.

I got the component in OK, but I have around 3500 users, so have immediately hit some performance issues as soon as I try to search the list. The table/page takes about 2sec to load which isn't fantastic, but is fine for my case currently. However as soon as I attempt to search, the page hangs for around 10-20sec or so whilst it tries to filter the rows.

I began looking at adding a couple of new optional props to the table blade file to try to help:
- search_field > string - to restrict the filterTable search text comparisons to specific td's based on a new data attribute that matches the given string
- search_debounce > integer - time (milliseconds) to wait after input to the search field before actually running the filterTable function
- search_minLength > integer - minimum number of characters required before filterSearch would be called

However in the short time I've looked at it, the filterSearch function still takes 10-20sec to filter out the rows.

So before I put too much time into it, I wanted to ask if there were already any other ideas for how searchable tables with large data sets should be handled? Some thoughts come to mind such as:
- simply trying to further optimise the search and DOM updates code as above
- having some sort of search_route prop where a route could be specified. The component could send a couple of request parameters to that route, receive back a new list, and re-render the table or just the tbody in place

The second method there would put the filtering load back onto the server side which may not be ideal, but on the other hand it would also open up the opportunity for even better features for the table, such as being able to handle data pagination. This would be a big help for my situation (I have a few places in my project where I have quite large lists that I'd like to be searchable), but I understand that this method might not quite align with what this project is aimed at, which seems to be more about the frontend/UI rather than integrations with the backend.

Cheers
Nathan

**Comment by mkocansey** [comment]
Hey @ntbutler-nbcs thanks for giving BladewindUI a try and being very elaborate with your issue. 

I agree, the searchable tables need some speed improvements and you raise some good points on how to achieve this. I honestly never tried this with a large dataset. I'll do that and see how to improve the table. You're very much welcome to help as well.

You're right about your last point as well. This library focuses on handling everything on the frontend without interfering with users backend code.

**Comment by ntbutler-nbcs** [comment]
Hey @mkocansey 

As a start, what I've been playing around with is this as below (certainly needs work, but it's a start...)

1. Adding the new props and validation rules for them:
```php
@props([
    ...
    'search_field' => null,
    'search_debounce' => 0,
    'search_min_length' => 0,
    ...
])
@php
    ...
    $search_field = filter_var($search_field, FILTER_SANITIZE_STRING);
    $search_debounce = filter_var($search_debounce, FILTER_VALIDATE_INT);
    $search_min_length = filter_var($search_min_length, FILTER_VALIDATE_INT);
    ...
```

2. Dumping the $data array into a javascript variable, so I can use that to handle the filtering later:
```javascript
<script>
    let tableData = {!! json_encode($data) !!};
</script>
```

3. In the helpers.js file, adding an array partition function to use later to split the tableData array into a list of elements to hide and a list to show:
```javascript
const partition = (arr, fn) => {
    return arr.reduce(
      (acc, val, i, arr) => {
        acc[fn(val, i, arr) ? 0 : 1].push(val);
        return acc;
      },
      [[], []]
    );
}
```

4. In helpers.js, adding another intermediary function for the search box to call on input
```javascript

/**
 * Filter a table based on keyword, .
 * @param {string} keyword - The keyword to filter table by.
 * @param {string} table - The css class (name) of the table to filter.
 * @param {string} field - The field to search.
 * @param {int} delay - Number of milliseconds to debouce the search.
 * @return {function} - The debounced search function to be run
 */
const filterTableDebounced = (keyword, table, field = null, delay = 0, minLength = 0) => {
    if (keyword.length >= minLength) {
        let timerId;
        return (...args) => {
            clearTimeout(timerId);
            timerId = setTimeout( () => filterTable(keyword, table, field), delay);
        };
    } else {
        document.querySelectorAll(`${table} tbody tr.hidden`).forEach((tr) => {
            unhide(tr, true);
        });
    }
    return () => {};
};
```

5. Update the filterTable function in  helpers.jd to support searching using a field if one is specified
```javascript
/**
 * Filter a table based on keyword.
 * @param {string} keyword - The keyword to filter table by.
 * @param {string} table - The css class (name) of the table to filter.
 * @param {string} field - The field to search.
 * @return {void}
 */
var filterTable = (keyword, table, field) => {
    const [showList, hideList] = partition(tableData, (row) => {
        if (field){
            return row[field].toLowerCase().match(keyword.toLowerCase());
        } else {
            return Object.values(row).toString().match(keyword.toLowerCase());
        }
    });

    hideList.forEach( (row) => {
        hide(domEl(`${table} tbody tr[data-id='${row.id}']`), true);
    });
    showList.forEach( (row) => {
        const elem = domEl(`${table} tbody tr[data-id='${row.id}'].hidden`);
        if (elem){
            unhide(elem, true);
        }
    });
}

```

6. Back in the table.blade.php file, updating the search bar to use the new debounced function. NOTE: I also updated this to use onInput instead of onkeyup, as I was finding the function was triggering more often than desired
```php

        @if($searchable)
            <div class="bw-table-filter-bar">
                <x-bladewind::input
                        name="bw-search-{{$name}}"
                        placeholder="{{$search_placeholder}}"
                        onInput="filterTableDebounced(this.value, 'table.{{$name}}', '{{$search_field}}', {{$search_debounce}}, {{$search_min_length}})();"
                        add_clearing="false"
                        class="!mb-0 focus:!border-slate-300 !pl-9 !py-3"
                        clearable="true"
                        prefix_is_icon="true"
                        prefix="magnifying-glass"/>
            </div>
        @endif

```

There is still a lot that can be improved such as:
- It doesn't yet handle data that doesn't have an id property on it's objects already (the uniqId generated for each HTML row isn't stored in the javascript variable, affecting how I'm showing/hiding rows)
- Only running the hide function on rows that are not hidden
- The clearTimeout's aren't working correctly causing some issues, but I haven't yet dug into this and I've not played alot with JS timeouts.
- Filtering out unneeded columns when storing the $data array into Javascript, if the include_columns or exclude_columns props are used

With that said, the speed improvements so far have been really good - filtering around 3800 records now takes me about 0.8sec, with a bit of a freeze to the UI as it applies all of the CSS changes, but it's progress 😄

**Comment by mkocansey** [comment]
@ntbutler-nbcs wow.. this is great. Would be great if you can work this into the library and submit a PR. What do you think>

**Comment by ntbutler-nbcs** [comment]
No problem - I wasn't sure I'd have time to work on it this quickly but I've just put through a new PR #373 with my proposed changes 😁

**Comment by mkocansey** [comment]
@ntbutler-nbcs 
There are a few errors popping up in the console but I will get them fixed. Your code has given me enough of a head start.
