### ISSUE TITLE
Css modification on components out of bladewind scope

### ISSUE THREAD

**Issue by olivier-perrier** [mkocansey/bladewind#37]
bladewind css file brings modification on native table.
bladewind-ui.min.css
thead>tr>th {
    border-top-width: 1px;
    border-color: rgb(229 231 235 / 0.2);
    --tw-bg-opacity: 1;
    background-color: rgb(255 255 255 / var(--tw-bg-opacity));
    ....
Should it use a specific id or class of table bladewind component to avoid doing modifications on non baldewind compoenents ?

**Comment by mkocansey** [comment]
@olivier-perrier 
Yes it should. Thanks for raising this

**Comment by mkocansey** [comment]
@olivier-perrier this is fixed in v1.1.3. 
Kindly `composer update` and 
`php artisan vendor:publish --provider="Mkocansey\Bladewind\BladewindServiceProvider" --tag=assets --force`
