### ISSUE TITLE
Theme Switcher not load

### ISSUE THREAD

**Issue by rcurvello** [mkocansey/bladewind#375]
The "Theme Switcher" is not loading... not even on the https://bladewindui.com website, the component is "hidden", as shown in the image. The same problem occurs locally.

![themeSwitcher](https://github.com/user-attachments/assets/48f5d210-7f16-4fee-8503-5524bbe77ba9)

BladewindUI version: v2.7.1
PHP version: Php 8.2.0
OS: Windows
Browser type and version: Opera, Chrome, Firefox, Edge

**Comment by mkocansey** [comment]
Thanks @rcurvello for bringing this up. Will fix.

**Comment by jaguarman** [comment]
I can see the theme switcher but the whole page looks awkward in dark mode, see picture.
![bladewind-website](https://github.com/user-attachments/assets/d3f01df2-6fb3-49cc-8fe6-35ab8237bdb2)

**Comment by mkocansey** [comment]
@jaguarman Dark mode resolved

**Comment by mkocansey** [comment]
@rcurvello the theme switcher is showing now on the docs website. Can you confirm if you see it and if the Theme Switcher works for you now?

**Comment by rcurvello** [comment]
> @rcurvello the theme switcher is showing now on the docs website. Can you confirm if you see it and if the Theme Switcher works for you now?

For me, it still doesn't show.

![image](https://github.com/user-attachments/assets/95811538-d773-4c83-a0fe-d99d4d7c7ee2)

**Comment by jaguarman** [comment]
Works fine for me

Robson Curvello ***@***.***> schrieb am Fr., 25. Okt. 2024,
13:12:

**Comment by mkocansey** [comment]
@rcurvello Could it possibly be a cache problem. Can you try in another browser. I tried in chrome, safari, Firefox and I see the component in all three browsers.

**Comment by rcurvello** [comment]
I don't know, but I'm trying in Chrome, Opera, Opera GX, Firefox, and Brave on my computer, and I also tried on my phone; all of them have the same issue.

**Comment by mkocansey** [comment]
@rcurvello can you inspect element on the GitHub logo top right of the page and copy the HTML code for the DIV that contains all the top right elements. This will help me debug from here. thanks 

![Screenshot 2024-10-30 at 11 20 29](https://github.com/user-attachments/assets/196cf47f-010d-4e69-b796-051962e2f465)

**Comment by rcurvello** [comment]
@mkocansey Below is a print screen of the requested inspected element.
![image](https://github.com/user-attachments/assets/c4964024-c378-4b93-932e-d1002087fae4)

**Comment by mkocansey** [comment]
@rcurvello thanks for the screenshot. Really helped. Problem fixed in 2.7.3

**Comment by rcurvello** [comment]
@mkocansey Wow! Works fine now! Tks!
