### ISSUE TITLE
@lang laravel blade Code not working 

### ISSUE THREAD

**Issue by shakil-brl** [mkocansey/bladewind#39]
<x-bladewind::tab-heading name="notice" active="true" label={{ @lang('home.notice') }} />

**Comment by mkocansey** [comment]
@shakil-brl can you attach a screenshot of what you get as the error?

**Comment by mkocansey** [comment]
@shakil-brl 
You can do this in two ways

1. `<x-bladewind::tab-heading name="notice" active="true" label="@lang('home.notice')" />` 
     (no curly braces around @lang)

2. `<x-bladewind::tab-heading name="notice" active="true" label="{{ __('home.notice') }}" />`
