### ISSUE TITLE
Multiselect - automatic selection breaks on page refresh

### ISSUE THREAD

**Issue by bunny-x-bunny** [mkocansey/bladewind#393]
**Version:** 2.7.6

**Sample code:**
```html
<x-bladewind::select
  name="tags"
  multiple="true"
  selected_value="0"
  :data="[['label' => 'cat', 'value' => '0'], ['label' => 'dog', 'value' => '1']]"
/>
```

**Description:**
When refreshing page with F5, options provided via `selected_value` are ignored. Empty input is displayed. Further, it is impossible to select these values manually.
When refreshing page with disabled cache (Ctrl-Shift-F5), automatic selection works correctly, input contains all values from `selected_value`.
Perhaps this has something to do with html form autocomplete.
You can actually see this bug in action in docs themselves:
https://bladewindui.com/component/select#automatic

**Comment by mkocansey** [comment]
Thanks @bunny-x-bunny for raising this. Will fix asap.

**Comment by mkocansey** [comment]
@bunny-x-bunny I cant seem to reproduce this issue. I used the exact code you provided and also checked the docs pages. Everything works fine from this side. Safari. Chrome. Firefox. See attached video.


https://github.com/user-attachments/assets/cf9257ea-8cab-48b6-8a2b-83693d4fd38c

**Comment by bunny-x-bunny** [comment]
Seems Firefox specific. 

Tested on clean installs: 
Firefox 130.0, Win 11 => have bug
Firefox 130.0, Ubuntu 22.04 => have bug
Chrome 130.0 => no bug

I will see if I can debug it better once I have time.
