### ISSUE TITLE
Select should show selected_value in readonly/disabled mode

### ISSUE THREAD

**Issue by printpagestopdf** [mkocansey/bladewind#395]
If readonly or disabled is set on the select component, initial selected_value is not displayed. It would be great to display this in one of these states (or add a third one).

For sure it would be possible to use e.g. a div and only displaying the selected_value label for a readonly representation. But than I have to rebuild the whole logic of mapping value to label (could be an effort in a filtered list with non unique values).

In the moment I am solving this with an ugly workaround:
Added a new option "unselectable" and use it in select.js:

    activate = () => {
        if(this.unselectable !== true) {
            dom_el(this.clickArea).addEventListener('click', (e) => {
                unhide(this.itemsContainer);
            });
        }
        .................................................

**Comment by mkocansey** [comment]
Please provide your version of BladewindUI

**Comment by printpagestopdf** [comment]
> Please provide your version of BladewindUI

Sorry, forgot this.
composer.lock says: v2.6.4

**Comment by mkocansey** [comment]
Hey @printpagestopdf this was reported in #299 and been fixed since then. Please `composer update` to get the latest version of BladewindUI. Let me know if the problem still exists after the update.

**Comment by printpagestopdf** [comment]
Ups sorry, my fault with the old Version, but I am working on an installation that somebody else made (and controls). Please close this.
