### ISSUE TITLE
base64 textarea should be configurable in filepicker

### ISSUE THREAD

**Issue by printpagestopdf** [mkocansey/bladewind#396]
The base64 textarea is a very nice feature of filepicker. But there is one disadvantage of this: if post_max_size and upload_max_filesize are small (and on some hosters you are unable to control this), than it increases the amount of posted data.

So a wish would be to make this configurable by an option.

As a workaround I introduced in my modified component an attribute base64 (default true) and changed textarea:

<textarea class="b64-{{ $name }}@if($required) required @endif" @if($base64) name="b64_{{ $name }}" @endif></textarea>

Version by composer.lock says: v2.6.4

**Comment by mkocansey** [comment]
@printpagestopdf thanks for the suggestion. I have implemented this now and will be available in the next version.
