### ISSUE TITLE
Table Pagination and Sorting

### ISSUE THREAD

**Issue by adamlytics** [mkocansey/bladewind#400]
The table is great.  I have the server-side pagination figured out, but it would be great to have some controls for it, as well as enabling JavaScript pagination.  You'd be able to put in how many rows per page you want, and then it would display that amount and if it is great, there will be some sort of pagination at the bottom of the table.

In addition sorting would be great.  Again, it can be some sort of controls to add the sorting icon to the header, and then be able to control what happens when it is clicked.  It would be great to also support JavaScript sorting and have it update right away in addition to having a way to trigger server-side sorting.

**Comment by mkocansey** [comment]
Glad you like the table component @adamlytics. Will add this issue to the v2.8.x feature updates.
