### ISSUE TITLE
Add support for HTMLFormElement in the validateForm method

### ISSUE THREAD

**Issue by SofianeLasri** [mkocansey/bladewind#403]
Actually, we have to set a class to the form that we want to validate. This is good for "one time" usage or for validating only the forms we want, but it restricts a little bit the scope.

The idea would be to being able call the validateForm method with the HTMLFormElement instance of the form, just like this :

```js
const forms = document.getElementsByTagName('form');
for (let i = 0; i < forms.length; i++) {
    forms[i].addEventListener('submit', function (e) {
        e.preventDefault();
        let validationStatus = validateForm(this); // Here
        if (validationStatus) {
            this.submit();
        }
    });
}
```

With that, we would be able to fully 'automatize' the forms validation.

**Comment by mkocansey** [comment]
Sure @SofianeLasri this can be done and I'll add it to the next update. Just curious though. Are there use-case where you will have multiple forms on a page that all need to be validated at once on click of one button?

**Comment by SofianeLasri** [comment]
No I actually don't have one for this use case. But, my idea was to add this piece of code inside my view layout. Here, is is for my authenticaton pages. But I think that I will do the same for the dashboard layout were almost all the pages will contains forms. 

```blade
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title', 'Authentification')</title>
    <link href="{{ asset('vendor/bladewind/css/animate.min.css') }}" rel="stylesheet"/>
    <link href="{{ asset('vendor/bladewind/css/bladewind-ui.min.css') }}" rel="stylesheet"/>
    <script src="{{ asset('vendor/bladewind/js/helpers.js') }}"></script>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
<div class="min-h-screen flex flex-col justify-center items-center bg-gray-100">
    <x-bladewind.card class="w-full max-w-md">
        @yield('content')
    </x-bladewind.card>
</div>
<script type="text/javascript">
    dom_el('.validate-me').addEventListener('submit', function (e) {
        e.preventDefault();
        let validationStatus = validateForm('.validate-me');
        if (validationStatus) {
            this.submit();
        }
    });
</script>
</body>
</html>
```

**Comment by mkocansey** [comment]
@SofianeLasri if I understand you correctly, you simply want a way to validate forms by targeting the `form` tag instead of specific css classes assigned to the forms. Are we on the same page?
