### ISSUE TITLE
Centered content component is missing 3xl and 4xl classes

### ISSUE THREAD

**Issue by tuto1902** [mkocansey/bladewind#43]
I noticed that when using `big` and `xl` sizes for the centered-content component, the rendered div goes full width instead of staying in the desired max size. It appears that both `max-w-3xl` and `max-w-4xl` are not included inside `bladewind-ui.min.css`

I worked around this by installing Tailwind CSS in my Laravel project, modifying `resources/views/components/centered-content.blade.php` and adding the two missing classes to the empty div, like this:

````
<div class="max-w-7xl max-w-6xl max-w-2xl max-w-3xl max-w-4xl max-w-lg max-w-md"></div>
````

After running `npm run dev`, the problem was solved. But it would be nice if these two classes were already compiled.

**Comment by mkocansey** [comment]
@tuto1902 thanks for pointing this out. This is fixed in v1.2.3 (latest version)
