### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by abdelhamiderrahmouni** [mkocansey/bladewind#47]
The modals in phones look shrinked!

[Screenshot_20220615-131510.png](https://user-images.githubusercontent.com/26693672/173824542-7b0e771c-907f-4228-a481-2dadbeb689b5.png)

**Comment by mkocansey** [comment]
@abdelhamiderrahmouni This is fixed in the current Version (v1.2.5)

**Comment by abdelhamiderrahmouni** [comment]
Thank you brother. 
Great work of the package, i genuinely admire it.
