### ISSUE TITLE
Small typo in the Basic Card example...

### ISSUE THREAD

**Issue by macCesar** [mkocansey/bladewind#49]
**First of all... Excellent modules!!**

There is a small typo in the first Card example.

https://bladewindui.com/component/card

There is a slash at the end of the closing tag:

```html
<x-bladewind.card>
    // the card content goes here
</x-bladewind.card/> <-- Extra slash at the end
```

**Comment by mkocansey** [comment]
Many Thanks @macCesar for the compliments and flagging the typo. Getting it fixed
