### ISSUE TITLE
 No publishable resources for tag [assets].

### ISSUE THREAD

**Issue by rudaovel** [mkocansey/bladewind#61]
http://prntscr.com/hqjEfVNj-aGY
artisan vendor:publish --provider="Mkocansey\Bladewind\BladewindServiceProvider" --tag=assets --force

**Comment by mkocansey** [comment]
@rudaovel thanks for raising this. Will get it fixed

**Comment by mkocansey** [comment]
@rudaovel what version of BladewindUI are you on? `assets` was actually changed in an earlier version to `laravel-assets` so composer will automatically publish the assets once the package is pulled in or updated. The docs actually make a reference now to `laravel-assets`

**Comment by rudaovel** [comment]
> @rudaovel what version of BladewindUI are you on? was actually changed in an earlier version to so composer will automatically publish the assets once the package is pulled in or updated. The docs actually make a reference now to `assets``laravel-assets``laravel-assets`

0.19 version update v1.4.2 updated manually in the composer file and everything worked.

**Comment by mkocansey** [comment]
@rudaovel awesome to hear
