### ISSUE TITLE
It's not possible to style the text on a button

### ISSUE THREAD

**Issue by rabol** [mkocansey/bladewind#66]
It's not possible style text on the button e.g.

```
<x-bladewind::button size="tiny" color="red" class="font-bold text-black">Options</x-bladewind::button>
```
render a red button with white text, I would have expected a red button with bold black text

**Comment by mkocansey** [comment]
@rabol try `!text-black` and let me know if that works for you.

**Comment by rabol** [comment]
I'm sorry, it does not work

I think it's because the 'text' on a button is wrapped in a <span> tag

**Comment by mkocansey** [comment]
@rabol I have added the option to overwrite the button text css using `button_text_css`. In your case your code becomes 
`<x-bladewind::button size="tiny" color="red" button_text_css="font-bold text-black">Options</x-bladewind::button>`

You will need to `composer update` to 1.4.4. Please let me know how that goes for you.

**Comment by rabol** [comment]
Works, thanks
