### ISSUE TITLE
Missing component "meta" breaks the Blade views compilation

### ISSUE THREAD

**Issue by avgust1111** [mkocansey/bladewind#70]
**Steps to reproduce**

1. Set up a new Laravel project
2. Install the Bladewind
3. Run the console command `artisan view:cache`

Expected result
The compilation is finished correctly

Actual result
The compilation failed due to the error
`Unable to locate a class or view for component [meta]`

Additional details
[log.txt](https://github.com/mkocansey/bladewind/files/9839752/log.txt)
The log file example is attached
Here is the component, which causes the issue
https://github.com/mkocansey/bladewind/blob/v1.4.5/src/resources/views/components/app.blade.php#L5

**Comment by avgust1111** [comment]
Please, note: the same issue occurred with missing components `notification` and `footer` in the same template

**Comment by mkocansey** [comment]
Thanks @avgust1111 .. looking into this now

**Comment by mkocansey** [comment]
@avgust1111 please composer updated

**Comment by macCesar** [comment]
Still the same problem after `composer update`, using `Laravel Framework 8.83.26`

**Comment by macCesar** [comment]
Sorry.. removed `components/bladewind` in order for composer to re-publish the folder.

Now the issue is gone!! 👍🏻
