### ISSUE TITLE
Mutiple Tab groups In Same Page not working correctly

### ISSUE THREAD

**Issue by prageeth-peiris** [mkocansey/bladewind#72]
Hi,

Thanks for your great work ! You save us lot of time !

I am displaying multiple tab groups in same page. when  I change tabs in one group  other group's active tab get deselected.  Is this default behavior ?
Or multiple tab groups are not  supported?

**Comment by mkocansey** [comment]
Hi @prageeth-peiris .. I am glad the components are saving you time. 
You can actually use multiple tab groups on the same page. You can see on the docs page that I am using several tab groups on the tab documentation page. 

The important part is to give each tad group a unique name

`<x-bladewind.tab-group name="group-1">`

`<x-bladewind.tab-group name="group-2">`

**Comment by prageeth-peiris** [comment]
@mkocansey  I am  noticing same behavior in docs page  too.

Steps To Reproduce : 

1) Go to Tabs Page (https://bladewindui.com/component/tab)

2) Then click on  "Pending Loans" tab. Now it is selected. (First Tab Group)
3) Click on "Sam Carter" tab (Second Tab Group)
4) Now the "Pending Loans" tab has been deselected. (First Tab Group)

But those tab groups has different names.

Can you please check this?

**Comment by mkocansey** [comment]
Oh you're right @prageeth-peiris. I'll check and fix

**Comment by prageeth-peiris** [comment]
Hi @mkocansey !

Just checking,  whether you had time to look into this?

**Comment by mkocansey** [comment]
@prageeth-peiris I'll push a couple of updates including this fix by Friday. Will notify you once it's live.

**Comment by mkocansey** [comment]
@prageeth-peiris you can `composer update` to pull in v1.4.8
