### ISSUE TITLE
File picker doesn't work if name is "logo"

### ISSUE THREAD

**Issue by amenline** [mkocansey/bladewind#8]
The file picker strangely doesn't respond to click when the name attribute is set to "logo" as shown in the code below.

`<x-bladewind::filepicker name="logo" placeholder="Logo" accepted_file_types=".png, .jpg" required="true" />`

I'm using 
- Laravel 9.2
- PHP 8.0.2
- TailwindCSS 3.0.18

**Comment by mkocansey** [comment]
[https://bladewindui.com/component/filepicker](The FIlepicker) documentation page has been updated to use `name="logo"` for the first example. It works perfectly. You can 'Inspect Element', search for name="logo" to see it in use.
