### ISSUE TITLE
Loss of custom change on assets

### ISSUE THREAD

**Issue by sh4msi** [mkocansey/bladewind#83]
hi,
Unfortunately, with every change in the composer, all assets are copied and rewritten from the beginning, which causes the loss of custom changes.

```
  Copying directory [E:\laragon\www\x\vendor\mkocansey\bladewind\src\resources\views\components] to [E:\laragon\www\x\resources\views\components\bladewind]  DONE
  Copying directory [E:\laragon\www\x\vendor\mkocansey\bladewind\src\resources\lang] to [E:\laragon\www\x\lang]  DONE
  Copying directory [E:\laragon\www\x\vendor\mkocansey\bladewind\src\resources\assets\compiled] to [E:\laragon\www\x\public\bladewind]  DONE
```

**Comment by mkocansey** [comment]
@sh4msi you can `composer update` to pull in the update. Auto publishing of assets has been disabled. 

[https://bladewindui.com/customization](https://bladewindui.com/customization)
