### ISSUE TITLE
onchange and onkeyup attribute is not working for textarea

### ISSUE THREAD

**Issue by razachisibrahimah** [mkocansey/bladewind#9]
The Bladewind textarea component does not respond to attributes such as onchange and onkeyup as shown in the below code

`<x-bladewind.textarea required="true" label="message"   onchange="countChar(this)"  onkeyup="countChar(this)"  />`

using below versions
Laravel 9.2
PHP 8.0.2
TailwindCSS 3.0.18

**Comment by mkocansey** [comment]
Please provide a description for this issue

**Comment by mkocansey** [comment]
Fixed in v0.1.7
